/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { DeleteProjectIdMutationResponse, DeleteProjectIdPathParams } from '../../types/DeleteProjectId.ts'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import { useMutation } from '@tanstack/react-query'

export const deleteProjectIdMutationKey = () => [{ url: '/project/{id}' }] as const

export type DeleteProjectIdMutationKey = ReturnType<typeof deleteProjectIdMutationKey>

/**
 * @summary Deletar projeto
 * {@link /project/:id}
 */
export async function deleteProjectId(id: DeleteProjectIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<DeleteProjectIdMutationResponse, ResponseErrorConfig<Error>, unknown>({ method: 'DELETE', url: `/project/${id}`, ...requestConfig })
  return res
}

/**
 * @summary Deletar projeto
 * {@link /project/:id}
 */
export function useDeleteProjectId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<DeleteProjectIdMutationResponse>,
      ResponseErrorConfig<Error>,
      { id: DeleteProjectIdPathParams['id'] },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? deleteProjectIdMutationKey()

  return useMutation<ResponseConfig<DeleteProjectIdMutationResponse>, ResponseErrorConfig<Error>, { id: DeleteProjectIdPathParams['id'] }, TContext>(
    {
      mutationFn: async ({ id }) => {
        return deleteProjectId(id, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}