/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { DeleteUserIdMutationResponse, DeleteUserIdPathParams } from '../../types/DeleteUserId.ts'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import { useMutation } from '@tanstack/react-query'

export const deleteUserIdMutationKey = () => [{ url: '/user/{id}' }] as const

export type DeleteUserIdMutationKey = ReturnType<typeof deleteUserIdMutationKey>

/**
 * @summary Deletar usuário
 * {@link /user/:id}
 */
export async function deleteUserId(id: DeleteUserIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<DeleteUserIdMutationResponse, ResponseErrorConfig<Error>, unknown>({ method: 'DELETE', url: `/user/${id}`, ...requestConfig })
  return res
}

/**
 * @summary Deletar usuário
 * {@link /user/:id}
 */
export function useDeleteUserId<TContext>(
  options: {
    mutation?: UseMutationOptions<ResponseConfig<DeleteUserIdMutationResponse>, ResponseErrorConfig<Error>, { id: DeleteUserIdPathParams['id'] }, TContext> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? deleteUserIdMutationKey()

  return useMutation<ResponseConfig<DeleteUserIdMutationResponse>, ResponseErrorConfig<Error>, { id: DeleteUserIdPathParams['id'] }, TContext>(
    {
      mutationFn: async ({ id }) => {
        return deleteUserId(id, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}