/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetUserQueryResponse } from '../../types/GetUser.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getUserQueryKey = () => [{ url: '/user' }] as const

export type GetUserQueryKey = ReturnType<typeof getUserQueryKey>

/**
 * @summary Listar usuários
 * {@link /user}
 */
export async function getUser(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetUserQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/user`, ...requestConfig })
  return res
}

export function getUserQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getUserQueryKey()
  return queryOptions<ResponseConfig<GetUserQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetUserQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getUser(config)
    },
  })
}

/**
 * @summary Listar usuários
 * {@link /user}
 */
export function useGetUser<
  TData = ResponseConfig<GetUserQueryResponse>,
  TQueryData = ResponseConfig<GetUserQueryResponse>,
  TQueryKey extends QueryKey = GetUserQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetUserQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getUserQueryKey()

  const query = useQuery(
    {
      ...(getUserQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}