/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetCompanyNameQueryResponse, GetCompanyNamePathParams } from '../../types/GetCompanyNameName.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getCompanyNameNameSuspenseQueryKey = (name: GetCompanyNamePathParams['name']) => [{ url: '/company/name/:name', params: { name: name } }] as const

export type GetCompanyNameNameSuspenseQueryKey = ReturnType<typeof getCompanyNameNameSuspenseQueryKey>

/**
 * @summary Buscar empresa por nome
 * {@link /company/name/:name}
 */
export async function getCompanyNameNameSuspense(name: GetCompanyNamePathParams['name'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetCompanyNameQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/company/name/${name}`, ...requestConfig })
  return res
}

export function getCompanyNameNameSuspenseQueryOptions(
  name: GetCompanyNamePathParams['name'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getCompanyNameNameSuspenseQueryKey(name)
  return queryOptions<ResponseConfig<GetCompanyNameQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetCompanyNameQueryResponse>, typeof queryKey>({
    enabled: !!name,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getCompanyNameNameSuspense(name, config)
    },
  })
}

/**
 * @summary Buscar empresa por nome
 * {@link /company/name/:name}
 */
export function useGetCompanyNameNameSuspense<
  TData = ResponseConfig<GetCompanyNameQueryResponse>,
  TQueryKey extends QueryKey = GetCompanyNameNameSuspenseQueryKey,
>(
  name: GetCompanyNamePathParams['name'],
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetCompanyNameQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getCompanyNameNameSuspenseQueryKey(name)

  const query = useSuspenseQuery(
    {
      ...(getCompanyNameNameSuspenseQueryOptions(name, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}