/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetCertificatesQueryResponse } from '../../types/GetCertificates.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getCertificatesQueryKey = () => [{ url: '/certificates' }] as const

export type GetCertificatesQueryKey = ReturnType<typeof getCertificatesQueryKey>

/**
 * @summary Listar certificados
 * {@link /certificates}
 */
export async function getCertificates(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetCertificatesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/certificates`, ...requestConfig })
  return res
}

export function getCertificatesQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getCertificatesQueryKey()
  return queryOptions<ResponseConfig<GetCertificatesQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetCertificatesQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getCertificates(config)
    },
  })
}

/**
 * @summary Listar certificados
 * {@link /certificates}
 */
export function useGetCertificates<
  TData = ResponseConfig<GetCertificatesQueryResponse>,
  TQueryData = ResponseConfig<GetCertificatesQueryResponse>,
  TQueryKey extends QueryKey = GetCertificatesQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetCertificatesQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getCertificatesQueryKey()

  const query = useQuery(
    {
      ...(getCertificatesQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}