/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetUserQueryResponse } from '../../types/GetUser.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getUserSuspenseQueryKey = () => [{ url: '/user' }] as const

export type GetUserSuspenseQueryKey = ReturnType<typeof getUserSuspenseQueryKey>

/**
 * @summary Listar usuários
 * {@link /user}
 */
export async function getUserSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetUserQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/user`, ...requestConfig })
  return res
}

export function getUserSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getUserSuspenseQueryKey()
  return queryOptions<ResponseConfig<GetUserQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetUserQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getUserSuspense(config)
    },
  })
}

/**
 * @summary Listar usuários
 * {@link /user}
 */
export function useGetUserSuspense<TData = ResponseConfig<GetUserQueryResponse>, TQueryKey extends QueryKey = GetUserSuspenseQueryKey>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetUserQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getUserSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(getUserSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}