/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetCertificatesTitleQueryResponse, GetCertificatesTitlePathParams } from '../../types/GetCertificatesTitleTitle.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getCertificatesTitleTitleQueryKey = (title: GetCertificatesTitlePathParams['title']) =>
  [{ url: '/certificates/title/:title', params: { title: title } }] as const

export type GetCertificatesTitleTitleQueryKey = ReturnType<typeof getCertificatesTitleTitleQueryKey>

/**
 * @summary Buscar certificado por título
 * {@link /certificates/title/:title}
 */
export async function getCertificatesTitleTitle(
  title: GetCertificatesTitlePathParams['title'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetCertificatesTitleQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/certificates/title/${title}`,
    ...requestConfig,
  })
  return res
}

export function getCertificatesTitleTitleQueryOptions(
  title: GetCertificatesTitlePathParams['title'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getCertificatesTitleTitleQueryKey(title)
  return queryOptions<
    ResponseConfig<GetCertificatesTitleQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetCertificatesTitleQueryResponse>,
    typeof queryKey
  >({
    enabled: !!title,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getCertificatesTitleTitle(title, config)
    },
  })
}

/**
 * @summary Buscar certificado por título
 * {@link /certificates/title/:title}
 */
export function useGetCertificatesTitleTitle<
  TData = ResponseConfig<GetCertificatesTitleQueryResponse>,
  TQueryData = ResponseConfig<GetCertificatesTitleQueryResponse>,
  TQueryKey extends QueryKey = GetCertificatesTitleTitleQueryKey,
>(
  title: GetCertificatesTitlePathParams['title'],
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetCertificatesTitleQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getCertificatesTitleTitleQueryKey(title)

  const query = useQuery(
    {
      ...(getCertificatesTitleTitleQueryOptions(title, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}