/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetAuthMeQueryResponse } from '../../types/GetAuthMe.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getAuthMeInfiniteQueryKey = () => [{ url: '/auth/me' }] as const

export type GetAuthMeInfiniteQueryKey = ReturnType<typeof getAuthMeInfiniteQueryKey>

/**
 * @summary Buscar usuário autenticado
 * {@link /auth/me}
 */
export async function getAuthMeInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetAuthMeQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/auth/me`, ...requestConfig })
  return res
}

export function getAuthMeInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getAuthMeInfiniteQueryKey()
  return infiniteQueryOptions<ResponseConfig<GetAuthMeQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetAuthMeQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getAuthMeInfinite(config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * @summary Buscar usuário autenticado
 * {@link /auth/me}
 */
export function useGetAuthMeInfinite<
  TData = InfiniteData<ResponseConfig<GetAuthMeQueryResponse>>,
  TQueryData = ResponseConfig<GetAuthMeQueryResponse>,
  TQueryKey extends QueryKey = GetAuthMeInfiniteQueryKey,
>(
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetAuthMeQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getAuthMeInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(getAuthMeInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}