/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetCertificatesTitleQueryResponse, GetCertificatesTitlePathParams } from '../../types/GetCertificatesTitleTitle.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getCertificatesTitleTitleInfiniteQueryKey = (title: GetCertificatesTitlePathParams['title']) =>
  [{ url: '/certificates/title/:title', params: { title: title } }] as const

export type GetCertificatesTitleTitleInfiniteQueryKey = ReturnType<typeof getCertificatesTitleTitleInfiniteQueryKey>

/**
 * @summary Buscar certificado por título
 * {@link /certificates/title/:title}
 */
export async function getCertificatesTitleTitleInfinite(
  title: GetCertificatesTitlePathParams['title'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetCertificatesTitleQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/certificates/title/${title}`,
    ...requestConfig,
  })
  return res
}

export function getCertificatesTitleTitleInfiniteQueryOptions(
  title: GetCertificatesTitlePathParams['title'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getCertificatesTitleTitleInfiniteQueryKey(title)
  return infiniteQueryOptions<
    ResponseConfig<GetCertificatesTitleQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetCertificatesTitleQueryResponse>,
    typeof queryKey
  >({
    enabled: !!title,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getCertificatesTitleTitleInfinite(title, config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * @summary Buscar certificado por título
 * {@link /certificates/title/:title}
 */
export function useGetCertificatesTitleTitleInfinite<
  TData = InfiniteData<ResponseConfig<GetCertificatesTitleQueryResponse>>,
  TQueryData = ResponseConfig<GetCertificatesTitleQueryResponse>,
  TQueryKey extends QueryKey = GetCertificatesTitleTitleInfiniteQueryKey,
>(
  title: GetCertificatesTitlePathParams['title'],
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetCertificatesTitleQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getCertificatesTitleTitleInfiniteQueryKey(title)

  const query = useInfiniteQuery(
    {
      ...(getCertificatesTitleTitleInfiniteQueryOptions(title, config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}