/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetCertificatesIdQueryResponse, GetCertificatesIdPathParams } from '../../types/GetCertificatesId.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getCertificatesIdInfiniteQueryKey = (id: GetCertificatesIdPathParams['id']) => [{ url: '/certificates/:id', params: { id: id } }] as const

export type GetCertificatesIdInfiniteQueryKey = ReturnType<typeof getCertificatesIdInfiniteQueryKey>

/**
 * @summary Buscar certificado por ID
 * {@link /certificates/:id}
 */
export async function getCertificatesIdInfinite(id: GetCertificatesIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetCertificatesIdQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/certificates/${id}`,
    ...requestConfig,
  })
  return res
}

export function getCertificatesIdInfiniteQueryOptions(id: GetCertificatesIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getCertificatesIdInfiniteQueryKey(id)
  return infiniteQueryOptions<
    ResponseConfig<GetCertificatesIdQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetCertificatesIdQueryResponse>,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getCertificatesIdInfinite(id, config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * @summary Buscar certificado por ID
 * {@link /certificates/:id}
 */
export function useGetCertificatesIdInfinite<
  TData = InfiniteData<ResponseConfig<GetCertificatesIdQueryResponse>>,
  TQueryData = ResponseConfig<GetCertificatesIdQueryResponse>,
  TQueryKey extends QueryKey = GetCertificatesIdInfiniteQueryKey,
>(
  id: GetCertificatesIdPathParams['id'],
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetCertificatesIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getCertificatesIdInfiniteQueryKey(id)

  const query = useInfiniteQuery(
    {
      ...(getCertificatesIdInfiniteQueryOptions(id, config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}