/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetCertificatesTitleQueryResponse, GetCertificatesTitlePathParams } from '../../types/GetCertificatesTitleTitle.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getCertificatesTitleTitleSuspenseQueryKey = (title: GetCertificatesTitlePathParams['title']) =>
  [{ url: '/certificates/title/:title', params: { title: title } }] as const

export type GetCertificatesTitleTitleSuspenseQueryKey = ReturnType<typeof getCertificatesTitleTitleSuspenseQueryKey>

/**
 * @summary Buscar certificado por título
 * {@link /certificates/title/:title}
 */
export async function getCertificatesTitleTitleSuspense(
  title: GetCertificatesTitlePathParams['title'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetCertificatesTitleQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/certificates/title/${title}`,
    ...requestConfig,
  })
  return res
}

export function getCertificatesTitleTitleSuspenseQueryOptions(
  title: GetCertificatesTitlePathParams['title'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getCertificatesTitleTitleSuspenseQueryKey(title)
  return queryOptions<
    ResponseConfig<GetCertificatesTitleQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetCertificatesTitleQueryResponse>,
    typeof queryKey
  >({
    enabled: !!title,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getCertificatesTitleTitleSuspense(title, config)
    },
  })
}

/**
 * @summary Buscar certificado por título
 * {@link /certificates/title/:title}
 */
export function useGetCertificatesTitleTitleSuspense<
  TData = ResponseConfig<GetCertificatesTitleQueryResponse>,
  TQueryKey extends QueryKey = GetCertificatesTitleTitleSuspenseQueryKey,
>(
  title: GetCertificatesTitlePathParams['title'],
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetCertificatesTitleQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getCertificatesTitleTitleSuspenseQueryKey(title)

  const query = useSuspenseQuery(
    {
      ...(getCertificatesTitleTitleSuspenseQueryOptions(title, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}