/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetUserIdQueryResponse, GetUserIdPathParams } from '../../types/GetUserId.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getUserIdSuspenseQueryKey = (id: GetUserIdPathParams['id']) => [{ url: '/user/:id', params: { id: id } }] as const

export type GetUserIdSuspenseQueryKey = ReturnType<typeof getUserIdSuspenseQueryKey>

/**
 * @summary Buscar usuário por ID
 * {@link /user/:id}
 */
export async function getUserIdSuspense(id: GetUserIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetUserIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/user/${id}`, ...requestConfig })
  return res
}

export function getUserIdSuspenseQueryOptions(id: GetUserIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getUserIdSuspenseQueryKey(id)
  return queryOptions<ResponseConfig<GetUserIdQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetUserIdQueryResponse>, typeof queryKey>({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getUserIdSuspense(id, config)
    },
  })
}

/**
 * @summary Buscar usuário por ID
 * {@link /user/:id}
 */
export function useGetUserIdSuspense<TData = ResponseConfig<GetUserIdQueryResponse>, TQueryKey extends QueryKey = GetUserIdSuspenseQueryKey>(
  id: GetUserIdPathParams['id'],
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetUserIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getUserIdSuspenseQueryKey(id)

  const query = useSuspenseQuery(
    {
      ...(getUserIdSuspenseQueryOptions(id, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}