/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetProjectSlugQueryResponse, GetProjectSlugPathParams } from '../../types/GetProjectSlugSlug.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getProjectSlugSlugInfiniteQueryKey = (slug: GetProjectSlugPathParams['slug']) => [{ url: '/project/slug/:slug', params: { slug: slug } }] as const

export type GetProjectSlugSlugInfiniteQueryKey = ReturnType<typeof getProjectSlugSlugInfiniteQueryKey>

/**
 * @summary Buscar projeto por slug
 * {@link /project/slug/:slug}
 */
export async function getProjectSlugSlugInfinite(slug: GetProjectSlugPathParams['slug'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetProjectSlugQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/project/slug/${slug}`, ...requestConfig })
  return res
}

export function getProjectSlugSlugInfiniteQueryOptions(
  slug: GetProjectSlugPathParams['slug'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getProjectSlugSlugInfiniteQueryKey(slug)
  return infiniteQueryOptions<
    ResponseConfig<GetProjectSlugQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetProjectSlugQueryResponse>,
    typeof queryKey
  >({
    enabled: !!slug,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getProjectSlugSlugInfinite(slug, config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * @summary Buscar projeto por slug
 * {@link /project/slug/:slug}
 */
export function useGetProjectSlugSlugInfinite<
  TData = InfiniteData<ResponseConfig<GetProjectSlugQueryResponse>>,
  TQueryData = ResponseConfig<GetProjectSlugQueryResponse>,
  TQueryKey extends QueryKey = GetProjectSlugSlugInfiniteQueryKey,
>(
  slug: GetProjectSlugPathParams['slug'],
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetProjectSlugQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getProjectSlugSlugInfiniteQueryKey(slug)

  const query = useInfiniteQuery(
    {
      ...(getProjectSlugSlugInfiniteQueryOptions(slug, config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}