/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetProjectQueryResponse } from '../../types/GetProject.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getProjectSuspenseQueryKey = () => [{ url: '/project' }] as const

export type GetProjectSuspenseQueryKey = ReturnType<typeof getProjectSuspenseQueryKey>

/**
 * @summary Listar projetos
 * {@link /project}
 */
export async function getProjectSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetProjectQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/project`, ...requestConfig })
  return res
}

export function getProjectSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getProjectSuspenseQueryKey()
  return queryOptions<ResponseConfig<GetProjectQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetProjectQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getProjectSuspense(config)
    },
  })
}

/**
 * @summary Listar projetos
 * {@link /project}
 */
export function useGetProjectSuspense<TData = ResponseConfig<GetProjectQueryResponse>, TQueryKey extends QueryKey = GetProjectSuspenseQueryKey>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetProjectQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getProjectSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(getProjectSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}