/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetCompanyNameQueryResponse, GetCompanyNamePathParams } from '../../types/GetCompanyNameName.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getCompanyNameNameInfiniteQueryKey = (name: GetCompanyNamePathParams['name']) => [{ url: '/company/name/:name', params: { name: name } }] as const

export type GetCompanyNameNameInfiniteQueryKey = ReturnType<typeof getCompanyNameNameInfiniteQueryKey>

/**
 * @summary Buscar empresa por nome
 * {@link /company/name/:name}
 */
export async function getCompanyNameNameInfinite(name: GetCompanyNamePathParams['name'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetCompanyNameQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/company/name/${name}`, ...requestConfig })
  return res
}

export function getCompanyNameNameInfiniteQueryOptions(
  name: GetCompanyNamePathParams['name'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getCompanyNameNameInfiniteQueryKey(name)
  return infiniteQueryOptions<
    ResponseConfig<GetCompanyNameQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetCompanyNameQueryResponse>,
    typeof queryKey
  >({
    enabled: !!name,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getCompanyNameNameInfinite(name, config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * @summary Buscar empresa por nome
 * {@link /company/name/:name}
 */
export function useGetCompanyNameNameInfinite<
  TData = InfiniteData<ResponseConfig<GetCompanyNameQueryResponse>>,
  TQueryData = ResponseConfig<GetCompanyNameQueryResponse>,
  TQueryKey extends QueryKey = GetCompanyNameNameInfiniteQueryKey,
>(
  name: GetCompanyNamePathParams['name'],
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetCompanyNameQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getCompanyNameNameInfiniteQueryKey(name)

  const query = useInfiniteQuery(
    {
      ...(getCompanyNameNameInfiniteQueryOptions(name, config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}