/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetUserIdQueryResponse, GetUserIdPathParams } from '../../types/GetUserId.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getUserIdInfiniteQueryKey = (id: GetUserIdPathParams['id']) => [{ url: '/user/:id', params: { id: id } }] as const

export type GetUserIdInfiniteQueryKey = ReturnType<typeof getUserIdInfiniteQueryKey>

/**
 * @summary Buscar usuário por ID
 * {@link /user/:id}
 */
export async function getUserIdInfinite(id: GetUserIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetUserIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/user/${id}`, ...requestConfig })
  return res
}

export function getUserIdInfiniteQueryOptions(id: GetUserIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getUserIdInfiniteQueryKey(id)
  return infiniteQueryOptions<ResponseConfig<GetUserIdQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetUserIdQueryResponse>, typeof queryKey>({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getUserIdInfinite(id, config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * @summary Buscar usuário por ID
 * {@link /user/:id}
 */
export function useGetUserIdInfinite<
  TData = InfiniteData<ResponseConfig<GetUserIdQueryResponse>>,
  TQueryData = ResponseConfig<GetUserIdQueryResponse>,
  TQueryKey extends QueryKey = GetUserIdInfiniteQueryKey,
>(
  id: GetUserIdPathParams['id'],
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetUserIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getUserIdInfiniteQueryKey(id)

  const query = useInfiniteQuery(
    {
      ...(getUserIdInfiniteQueryOptions(id, config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}