/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetCompanyIdQueryResponse, GetCompanyIdPathParams } from '../../types/GetCompanyId.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getCompanyIdQueryKey = (id: GetCompanyIdPathParams['id']) => [{ url: '/company/:id', params: { id: id } }] as const

export type GetCompanyIdQueryKey = ReturnType<typeof getCompanyIdQueryKey>

/**
 * @summary Buscar empresa por ID
 * {@link /company/:id}
 */
export async function getCompanyId(id: GetCompanyIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetCompanyIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/company/${id}`, ...requestConfig })
  return res
}

export function getCompanyIdQueryOptions(id: GetCompanyIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getCompanyIdQueryKey(id)
  return queryOptions<ResponseConfig<GetCompanyIdQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetCompanyIdQueryResponse>, typeof queryKey>({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getCompanyId(id, config)
    },
  })
}

/**
 * @summary Buscar empresa por ID
 * {@link /company/:id}
 */
export function useGetCompanyId<
  TData = ResponseConfig<GetCompanyIdQueryResponse>,
  TQueryData = ResponseConfig<GetCompanyIdQueryResponse>,
  TQueryKey extends QueryKey = GetCompanyIdQueryKey,
>(
  id: GetCompanyIdPathParams['id'],
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetCompanyIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getCompanyIdQueryKey(id)

  const query = useQuery(
    {
      ...(getCompanyIdQueryOptions(id, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}