/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetCompanyQueryResponse } from '../../types/GetCompany.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getCompanyInfiniteQueryKey = () => [{ url: '/company' }] as const

export type GetCompanyInfiniteQueryKey = ReturnType<typeof getCompanyInfiniteQueryKey>

/**
 * @summary Listar empresas
 * {@link /company}
 */
export async function getCompanyInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetCompanyQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/company`, ...requestConfig })
  return res
}

export function getCompanyInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getCompanyInfiniteQueryKey()
  return infiniteQueryOptions<ResponseConfig<GetCompanyQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetCompanyQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getCompanyInfinite(config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * @summary Listar empresas
 * {@link /company}
 */
export function useGetCompanyInfinite<
  TData = InfiniteData<ResponseConfig<GetCompanyQueryResponse>>,
  TQueryData = ResponseConfig<GetCompanyQueryResponse>,
  TQueryKey extends QueryKey = GetCompanyInfiniteQueryKey,
>(
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetCompanyQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getCompanyInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(getCompanyInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}