/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetProjectQueryResponse } from '../../types/GetProject.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getProjectQueryKey = () => [{ url: '/project' }] as const

export type GetProjectQueryKey = ReturnType<typeof getProjectQueryKey>

/**
 * @summary Listar projetos
 * {@link /project}
 */
export async function getProject(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetProjectQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/project`, ...requestConfig })
  return res
}

export function getProjectQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getProjectQueryKey()
  return queryOptions<ResponseConfig<GetProjectQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetProjectQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getProject(config)
    },
  })
}

/**
 * @summary Listar projetos
 * {@link /project}
 */
export function useGetProject<
  TData = ResponseConfig<GetProjectQueryResponse>,
  TQueryData = ResponseConfig<GetProjectQueryResponse>,
  TQueryKey extends QueryKey = GetProjectQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetProjectQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getProjectQueryKey()

  const query = useQuery(
    {
      ...(getProjectQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}