/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetUserIdQueryResponse, GetUserIdPathParams } from '../../types/GetUserId.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getUserIdQueryKey = (id: GetUserIdPathParams['id']) => [{ url: '/user/:id', params: { id: id } }] as const

export type GetUserIdQueryKey = ReturnType<typeof getUserIdQueryKey>

/**
 * @summary Buscar usuário por ID
 * {@link /user/:id}
 */
export async function getUserId(id: GetUserIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetUserIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/user/${id}`, ...requestConfig })
  return res
}

export function getUserIdQueryOptions(id: GetUserIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getUserIdQueryKey(id)
  return queryOptions<ResponseConfig<GetUserIdQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetUserIdQueryResponse>, typeof queryKey>({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getUserId(id, config)
    },
  })
}

/**
 * @summary Buscar usuário por ID
 * {@link /user/:id}
 */
export function useGetUserId<
  TData = ResponseConfig<GetUserIdQueryResponse>,
  TQueryData = ResponseConfig<GetUserIdQueryResponse>,
  TQueryKey extends QueryKey = GetUserIdQueryKey,
>(
  id: GetUserIdPathParams['id'],
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetUserIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getUserIdQueryKey(id)

  const query = useQuery(
    {
      ...(getUserIdQueryOptions(id, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}