/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetProjectQueryResponse } from '../../types/GetProject.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getProjectInfiniteQueryKey = () => [{ url: '/project' }] as const

export type GetProjectInfiniteQueryKey = ReturnType<typeof getProjectInfiniteQueryKey>

/**
 * @summary Listar projetos
 * {@link /project}
 */
export async function getProjectInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetProjectQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/project`, ...requestConfig })
  return res
}

export function getProjectInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getProjectInfiniteQueryKey()
  return infiniteQueryOptions<ResponseConfig<GetProjectQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetProjectQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getProjectInfinite(config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * @summary Listar projetos
 * {@link /project}
 */
export function useGetProjectInfinite<
  TData = InfiniteData<ResponseConfig<GetProjectQueryResponse>>,
  TQueryData = ResponseConfig<GetProjectQueryResponse>,
  TQueryKey extends QueryKey = GetProjectInfiniteQueryKey,
>(
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetProjectQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getProjectInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(getProjectInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}