/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetCompanyQueryResponse } from '../../types/GetCompany.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getCompanyQueryKey = () => [{ url: '/company' }] as const

export type GetCompanyQueryKey = ReturnType<typeof getCompanyQueryKey>

/**
 * @summary Listar empresas
 * {@link /company}
 */
export async function getCompany(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetCompanyQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/company`, ...requestConfig })
  return res
}

export function getCompanyQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getCompanyQueryKey()
  return queryOptions<ResponseConfig<GetCompanyQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetCompanyQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getCompany(config)
    },
  })
}

/**
 * @summary Listar empresas
 * {@link /company}
 */
export function useGetCompany<
  TData = ResponseConfig<GetCompanyQueryResponse>,
  TQueryData = ResponseConfig<GetCompanyQueryResponse>,
  TQueryKey extends QueryKey = GetCompanyQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetCompanyQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getCompanyQueryKey()

  const query = useQuery(
    {
      ...(getCompanyQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}