/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetProjectSlugQueryResponse, GetProjectSlugPathParams } from '../../types/GetProjectSlugSlug.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getProjectSlugSlugSuspenseQueryKey = (slug: GetProjectSlugPathParams['slug']) => [{ url: '/project/slug/:slug', params: { slug: slug } }] as const

export type GetProjectSlugSlugSuspenseQueryKey = ReturnType<typeof getProjectSlugSlugSuspenseQueryKey>

/**
 * @summary Buscar projeto por slug
 * {@link /project/slug/:slug}
 */
export async function getProjectSlugSlugSuspense(slug: GetProjectSlugPathParams['slug'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetProjectSlugQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/project/slug/${slug}`, ...requestConfig })
  return res
}

export function getProjectSlugSlugSuspenseQueryOptions(
  slug: GetProjectSlugPathParams['slug'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getProjectSlugSlugSuspenseQueryKey(slug)
  return queryOptions<ResponseConfig<GetProjectSlugQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetProjectSlugQueryResponse>, typeof queryKey>({
    enabled: !!slug,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getProjectSlugSlugSuspense(slug, config)
    },
  })
}

/**
 * @summary Buscar projeto por slug
 * {@link /project/slug/:slug}
 */
export function useGetProjectSlugSlugSuspense<
  TData = ResponseConfig<GetProjectSlugQueryResponse>,
  TQueryKey extends QueryKey = GetProjectSlugSlugSuspenseQueryKey,
>(
  slug: GetProjectSlugPathParams['slug'],
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetProjectSlugQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getProjectSlugSlugSuspenseQueryKey(slug)

  const query = useSuspenseQuery(
    {
      ...(getProjectSlugSlugSuspenseQueryOptions(slug, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}