/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetUserQueryResponse } from '../../types/GetUser.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getUserInfiniteQueryKey = () => [{ url: '/user' }] as const

export type GetUserInfiniteQueryKey = ReturnType<typeof getUserInfiniteQueryKey>

/**
 * @summary Listar usuários
 * {@link /user}
 */
export async function getUserInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetUserQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/user`, ...requestConfig })
  return res
}

export function getUserInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getUserInfiniteQueryKey()
  return infiniteQueryOptions<ResponseConfig<GetUserQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetUserQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getUserInfinite(config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * @summary Listar usuários
 * {@link /user}
 */
export function useGetUserInfinite<
  TData = InfiniteData<ResponseConfig<GetUserQueryResponse>>,
  TQueryData = ResponseConfig<GetUserQueryResponse>,
  TQueryKey extends QueryKey = GetUserInfiniteQueryKey,
>(
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetUserQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getUserInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(getUserInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}