/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetCertificatesQueryResponse } from '../../types/GetCertificates.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getCertificatesSuspenseQueryKey = () => [{ url: '/certificates' }] as const

export type GetCertificatesSuspenseQueryKey = ReturnType<typeof getCertificatesSuspenseQueryKey>

/**
 * @summary Listar certificados
 * {@link /certificates}
 */
export async function getCertificatesSuspense(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetCertificatesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/certificates`, ...requestConfig })
  return res
}

export function getCertificatesSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getCertificatesSuspenseQueryKey()
  return queryOptions<ResponseConfig<GetCertificatesQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetCertificatesQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getCertificatesSuspense(config)
    },
  })
}

/**
 * @summary Listar certificados
 * {@link /certificates}
 */
export function useGetCertificatesSuspense<TData = ResponseConfig<GetCertificatesQueryResponse>, TQueryKey extends QueryKey = GetCertificatesSuspenseQueryKey>(
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetCertificatesQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getCertificatesSuspenseQueryKey()

  const query = useSuspenseQuery(
    {
      ...(getCertificatesSuspenseQueryOptions(config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}