/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetCompanyIdQueryResponse, GetCompanyIdPathParams } from '../../types/GetCompanyId.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getCompanyIdSuspenseQueryKey = (id: GetCompanyIdPathParams['id']) => [{ url: '/company/:id', params: { id: id } }] as const

export type GetCompanyIdSuspenseQueryKey = ReturnType<typeof getCompanyIdSuspenseQueryKey>

/**
 * @summary Buscar empresa por ID
 * {@link /company/:id}
 */
export async function getCompanyIdSuspense(id: GetCompanyIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetCompanyIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/company/${id}`, ...requestConfig })
  return res
}

export function getCompanyIdSuspenseQueryOptions(id: GetCompanyIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getCompanyIdSuspenseQueryKey(id)
  return queryOptions<ResponseConfig<GetCompanyIdQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetCompanyIdQueryResponse>, typeof queryKey>({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getCompanyIdSuspense(id, config)
    },
  })
}

/**
 * @summary Buscar empresa por ID
 * {@link /company/:id}
 */
export function useGetCompanyIdSuspense<TData = ResponseConfig<GetCompanyIdQueryResponse>, TQueryKey extends QueryKey = GetCompanyIdSuspenseQueryKey>(
  id: GetCompanyIdPathParams['id'],
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetCompanyIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getCompanyIdSuspenseQueryKey(id)

  const query = useSuspenseQuery(
    {
      ...(getCompanyIdSuspenseQueryOptions(id, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}