/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetCompanyIdQueryResponse, GetCompanyIdPathParams } from '../../types/GetCompanyId.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getCompanyIdInfiniteQueryKey = (id: GetCompanyIdPathParams['id']) => [{ url: '/company/:id', params: { id: id } }] as const

export type GetCompanyIdInfiniteQueryKey = ReturnType<typeof getCompanyIdInfiniteQueryKey>

/**
 * @summary Buscar empresa por ID
 * {@link /company/:id}
 */
export async function getCompanyIdInfinite(id: GetCompanyIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetCompanyIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/company/${id}`, ...requestConfig })
  return res
}

export function getCompanyIdInfiniteQueryOptions(id: GetCompanyIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getCompanyIdInfiniteQueryKey(id)
  return infiniteQueryOptions<
    ResponseConfig<GetCompanyIdQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetCompanyIdQueryResponse>,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getCompanyIdInfinite(id, config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * @summary Buscar empresa por ID
 * {@link /company/:id}
 */
export function useGetCompanyIdInfinite<
  TData = InfiniteData<ResponseConfig<GetCompanyIdQueryResponse>>,
  TQueryData = ResponseConfig<GetCompanyIdQueryResponse>,
  TQueryKey extends QueryKey = GetCompanyIdInfiniteQueryKey,
>(
  id: GetCompanyIdPathParams['id'],
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetCompanyIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getCompanyIdInfiniteQueryKey(id)

  const query = useInfiniteQuery(
    {
      ...(getCompanyIdInfiniteQueryOptions(id, config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}