/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetCertificatesQueryResponse } from '../../types/GetCertificates.ts'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getCertificatesInfiniteQueryKey = () => [{ url: '/certificates' }] as const

export type GetCertificatesInfiniteQueryKey = ReturnType<typeof getCertificatesInfiniteQueryKey>

/**
 * @summary Listar certificados
 * {@link /certificates}
 */
export async function getCertificatesInfinite(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetCertificatesQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/certificates`, ...requestConfig })
  return res
}

export function getCertificatesInfiniteQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getCertificatesInfiniteQueryKey()
  return infiniteQueryOptions<
    ResponseConfig<GetCertificatesQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetCertificatesQueryResponse>,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getCertificatesInfinite(config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * @summary Listar certificados
 * {@link /certificates}
 */
export function useGetCertificatesInfinite<
  TData = InfiniteData<ResponseConfig<GetCertificatesQueryResponse>>,
  TQueryData = ResponseConfig<GetCertificatesQueryResponse>,
  TQueryKey extends QueryKey = GetCertificatesInfiniteQueryKey,
>(
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetCertificatesQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getCertificatesInfiniteQueryKey()

  const query = useInfiniteQuery(
    {
      ...(getCertificatesInfiniteQueryOptions(config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}