/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { PostCompanyMutationRequest, PostCompanyMutationResponse } from '../../types/PostCompany.ts'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import { useMutation } from '@tanstack/react-query'

export const postCompanyMutationKey = () => [{ url: '/company' }] as const

export type PostCompanyMutationKey = ReturnType<typeof postCompanyMutationKey>

/**
 * @summary Criar empresa
 * {@link /company}
 */
export async function postCompany(
  data?: PostCompanyMutationRequest,
  config: Partial<RequestConfig<PostCompanyMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const formData = new FormData()
  if (data) {
    Object.keys(data).forEach((key) => {
      const value = data[key as keyof typeof data]
      if (typeof key === 'string' && (typeof value === 'string' || (value as Blob) instanceof Blob)) {
        formData.append(key, value as unknown as string)
      }
    })
  }
  const res = await request<PostCompanyMutationResponse, ResponseErrorConfig<Error>, PostCompanyMutationRequest>({
    method: 'POST',
    url: `/company`,
    data: formData,
    ...requestConfig,
    headers: { 'Content-Type': 'multipart/form-data', ...requestConfig.headers },
  })
  return res
}

/**
 * @summary Criar empresa
 * {@link /company}
 */
export function usePostCompany<TContext>(
  options: {
    mutation?: UseMutationOptions<ResponseConfig<PostCompanyMutationResponse>, ResponseErrorConfig<Error>, { data?: PostCompanyMutationRequest }, TContext> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig<PostCompanyMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postCompanyMutationKey()

  return useMutation<ResponseConfig<PostCompanyMutationResponse>, ResponseErrorConfig<Error>, { data?: PostCompanyMutationRequest }, TContext>(
    {
      mutationFn: async ({ data }) => {
        return postCompany(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}