/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { PostProjectMutationRequest, PostProjectMutationResponse } from '../../types/PostProject.ts'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import { useMutation } from '@tanstack/react-query'

export const postProjectMutationKey = () => [{ url: '/project' }] as const

export type PostProjectMutationKey = ReturnType<typeof postProjectMutationKey>

/**
 * @summary Criar projeto
 * {@link /project}
 */
export async function postProject(
  data?: PostProjectMutationRequest,
  config: Partial<RequestConfig<PostProjectMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const formData = new FormData()
  if (data) {
    Object.keys(data).forEach((key) => {
      const value = data[key as keyof typeof data]
      if (typeof key === 'string' && (typeof value === 'string' || (value as Blob) instanceof Blob)) {
        formData.append(key, value as unknown as string)
      }
    })
  }
  const res = await request<PostProjectMutationResponse, ResponseErrorConfig<Error>, PostProjectMutationRequest>({
    method: 'POST',
    url: `/project`,
    data: formData,
    ...requestConfig,
    headers: { 'Content-Type': 'multipart/form-data', ...requestConfig.headers },
  })
  return res
}

/**
 * @summary Criar projeto
 * {@link /project}
 */
export function usePostProject<TContext>(
  options: {
    mutation?: UseMutationOptions<ResponseConfig<PostProjectMutationResponse>, ResponseErrorConfig<Error>, { data?: PostProjectMutationRequest }, TContext> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig<PostProjectMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postProjectMutationKey()

  return useMutation<ResponseConfig<PostProjectMutationResponse>, ResponseErrorConfig<Error>, { data?: PostProjectMutationRequest }, TContext>(
    {
      mutationFn: async ({ data }) => {
        return postProject(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}