/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { PostCompaniesMutationRequest, PostCompaniesMutationResponse } from '../../types/PostCompanies'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import { useMutation } from '@tanstack/react-query'

export const postCompaniesMutationKey = () => [{ url: '/companies' }] as const

export type PostCompaniesMutationKey = ReturnType<typeof postCompaniesMutationKey>

/**
 * @summary Create a new company
 * {@link /companies}
 */
export async function postCompanies(
  data?: PostCompaniesMutationRequest,
  config: Partial<RequestConfig<PostCompaniesMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const formData = new FormData()
  if (data) {
    Object.keys(data).forEach((key) => {
      const value = data[key as keyof typeof data]
      if (typeof key === 'string' && (typeof value === 'string' || (value as Blob) instanceof Blob)) {
        formData.append(key, value as unknown as string)
      }
    })
  }
  const res = await request<PostCompaniesMutationResponse, ResponseErrorConfig<Error>, PostCompaniesMutationRequest>({
    method: 'POST',
    url: `/companies`,
    data: formData,
    ...requestConfig,
    headers: { 'Content-Type': 'multipart/form-data', ...requestConfig.headers },
  })
  return res
}

/**
 * @summary Create a new company
 * {@link /companies}
 */
export function usePostCompanies<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<PostCompaniesMutationResponse>,
      ResponseErrorConfig<Error>,
      { data?: PostCompaniesMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostCompaniesMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postCompaniesMutationKey()

  return useMutation<ResponseConfig<PostCompaniesMutationResponse>, ResponseErrorConfig<Error>, { data?: PostCompaniesMutationRequest }, TContext>(
    {
      mutationFn: async ({ data }) => {
        return postCompanies(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}