/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { PostProjectsMutationRequest, PostProjectsMutationResponse } from '../../types/PostProjects'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import { useMutation } from '@tanstack/react-query'

export const postProjectsMutationKey = () => [{ url: '/projects' }] as const

export type PostProjectsMutationKey = ReturnType<typeof postProjectsMutationKey>

/**
 * @summary Create a new project
 * {@link /projects}
 */
export async function postProjects(
  data?: PostProjectsMutationRequest,
  config: Partial<RequestConfig<PostProjectsMutationRequest>> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const formData = new FormData()
  if (data) {
    Object.keys(data).forEach((key) => {
      const value = data[key as keyof typeof data]
      if (typeof key === 'string' && (typeof value === 'string' || (value as Blob) instanceof Blob)) {
        formData.append(key, value as unknown as string)
      }
    })
  }
  const res = await request<PostProjectsMutationResponse, ResponseErrorConfig<Error>, PostProjectsMutationRequest>({
    method: 'POST',
    url: `/projects`,
    data: formData,
    ...requestConfig,
    headers: { 'Content-Type': 'multipart/form-data', ...requestConfig.headers },
  })
  return res
}

/**
 * @summary Create a new project
 * {@link /projects}
 */
export function usePostProjects<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<PostProjectsMutationResponse>,
      ResponseErrorConfig<Error>,
      { data?: PostProjectsMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig<PostProjectsMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postProjectsMutationKey()

  return useMutation<ResponseConfig<PostProjectsMutationResponse>, ResponseErrorConfig<Error>, { data?: PostProjectsMutationRequest }, TContext>(
    {
      mutationFn: async ({ data }) => {
        return postProjects(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}