/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetAuthMeQueryResponse, GetAuthMe401 } from '../../types/GetAuthMe'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getAuthMeQueryKey = () => [{ url: '/auth/me' }] as const

export type GetAuthMeQueryKey = ReturnType<typeof getAuthMeQueryKey>

/**
 * @summary Get current user info
 * {@link /auth/me}
 */
export async function getAuthMe(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetAuthMeQueryResponse, ResponseErrorConfig<GetAuthMe401>, unknown>({ method: 'GET', url: `/auth/me`, ...requestConfig })
  return res
}

export function getAuthMeQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getAuthMeQueryKey()
  return queryOptions<ResponseConfig<GetAuthMeQueryResponse>, ResponseErrorConfig<GetAuthMe401>, ResponseConfig<GetAuthMeQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getAuthMe(config)
    },
  })
}

/**
 * @summary Get current user info
 * {@link /auth/me}
 */
export function useGetAuthMe<
  TData = ResponseConfig<GetAuthMeQueryResponse>,
  TQueryData = ResponseConfig<GetAuthMeQueryResponse>,
  TQueryKey extends QueryKey = GetAuthMeQueryKey,
>(
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetAuthMeQueryResponse>, ResponseErrorConfig<GetAuthMe401>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getAuthMeQueryKey()

  const query = useQuery(
    {
      ...(getAuthMeQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetAuthMe401>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}