/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Attach = {
  /**
   * @type string | undefined, uuid
   */
  id?: string
  /**
   * @type string | undefined
   */
  path?: string
  /**
   * @type string | undefined
   */
  type?: string
  /**
   * @type string | undefined, date-time
   */
  createdAt?: string
  /**
   * @type string | undefined, date-time
   */
  updatedAt?: string
}