/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from './User'

export type AuthResult = {
  /**
   * @type string | undefined
   */
  access?: string
  /**
   * @type object | undefined
   */
  user?: User
}