/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Certificate = {
  /**
   * @type string | undefined
   */
  id?: string
  /**
   * @type string | undefined
   */
  title?: string
  /**
   * @type string | undefined
   */
  description?: string
  /**
   * @type string | undefined
   */
  platform?: string
  /**
   * @type string | undefined
   */
  url?: string
  /**
   * @type integer | undefined
   */
  workload?: number
  /**
   * @type string | undefined, date-time
   */
  createdAt?: string
  /**
   * @type string | undefined, date-time
   */
  updatedAt?: string
}