/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateLinksDto = {
  /**
   * @type string
   */
  github: string
  /**
   * @type string
   */
  figma: string
  /**
   * @type string
   */
  publicUrl: string
}