/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateUserDto = {
  /**
   * @type string
   */
  username: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  password: string
  /**
   * @type string | undefined
   */
  email?: string
  /**
   * @type string
   */
  role: string
}