/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateCertificateDto = {
  /**
   * @type string
   */
  title: string
  /**
   * @type string
   */
  description: string
  /**
   * @type string
   */
  platform: string
  /**
   * @type string, uri
   */
  url: string
  /**
   * @type integer
   */
  workload: number
}