/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateLinkDto } from './CreateLinkDto'

export type CreateProjectDto = {
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  shortDescription: string
  /**
   * @type string
   */
  description: string
  /**
   * @type array
   */
  skills: string[]
  /**
   * @type object
   */
  links: CreateLinkDto
  /**
   * @type string | undefined, uuid
   */
  companyId?: string
}