/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateLinksDto } from './CreateLinksDto.ts'

export type CreateProjectDto = {
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  slug: string
  /**
   * @type string
   */
  shortDescription: string
  /**
   * @type string
   */
  description: string
  /**
   * @type array
   */
  skills: string[]
  /**
   * @type string | undefined
   */
  companyId?: string
  /**
   * @type object
   */
  links: CreateLinksDto
}