/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const createUserDtoRoleEnum = {
  owner: 'owner',
  commun: 'commun',
} as const

export type CreateUserDtoRoleEnum = (typeof createUserDtoRoleEnum)[keyof typeof createUserDtoRoleEnum]

export type CreateUserDto = {
  /**
   * @type string
   */
  username: string
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  password: string
  /**
   * @type string, email
   */
  email: string
  /**
   * @type string
   */
  role: CreateUserDtoRoleEnum
}