/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateOwnerDto = {
  /**
   * @type string
   */
  name: string
  /**
   * @type string, email
   */
  email: string
  /**
   * @type string
   */
  phone: string
}