/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type CreateCompanyDto = {
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  description: string
  /**
   * @type string, date-time
   */
  startDate: string
  /**
   * @type string | undefined, date-time
   */
  endDate?: string
  /**
   * @type string
   */
  responsibleName: string
  /**
   * @type string
   */
  responsibleRole: string
}