/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteProjectIdPathParams = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description Projeto deletado
 */
export type DeleteProjectId200 = any

export type DeleteProjectIdMutationResponse = DeleteProjectId200

export type DeleteProjectIdMutation = {
  Response: DeleteProjectId200
  PathParams: DeleteProjectIdPathParams
  Errors: any
}