/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteCertificatesIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string
}

/**
 * @description Certificate deleted
 */
export type DeleteCertificatesId200 = any

export type DeleteCertificatesIdMutationResponse = DeleteCertificatesId200

export type DeleteCertificatesIdMutation = {
  Response: DeleteCertificatesId200
  PathParams: DeleteCertificatesIdPathParams
  Errors: any
}