/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteCompanyIdPathParams = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description Empresa deletada
 */
export type DeleteCompanyId200 = any

export type DeleteCompanyIdMutationResponse = DeleteCompanyId200

export type DeleteCompanyIdMutation = {
  Response: DeleteCompanyId200
  PathParams: DeleteCompanyIdPathParams
  Errors: any
}