/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteUsersIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string
}

/**
 * @description User deleted
 */
export type DeleteUsersId200 = any

export type DeleteUsersIdMutationResponse = DeleteUsersId200

export type DeleteUsersIdMutation = {
  Response: DeleteUsersId200
  PathParams: DeleteUsersIdPathParams
  Errors: any
}