/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteUserIdPathParams = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description Usuário deletado
 */
export type DeleteUserId200 = any

export type DeleteUserIdMutationResponse = DeleteUserId200

export type DeleteUserIdMutation = {
  Response: DeleteUserId200
  PathParams: DeleteUserIdPathParams
  Errors: any
}