/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteLinksIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string
}

/**
 * @description Link deleted
 */
export type DeleteLinksId200 = any

export type DeleteLinksIdMutationResponse = DeleteLinksId200

export type DeleteLinksIdMutation = {
  Response: DeleteLinksId200
  PathParams: DeleteLinksIdPathParams
  Errors: any
}