/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteOwnersIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string
}

/**
 * @description Owner deleted
 */
export type DeleteOwnersId200 = any

export type DeleteOwnersIdMutationResponse = DeleteOwnersId200

export type DeleteOwnersIdMutation = {
  Response: DeleteOwnersId200
  PathParams: DeleteOwnersIdPathParams
  Errors: any
}