/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from './User'

/**
 * @description User info
 */
export type GetAuthMe200 = User

/**
 * @description Unauthorized
 */
export type GetAuthMe401 = any

export type GetAuthMeQueryResponse = GetAuthMe200

export type GetAuthMeQuery = {
  Response: GetAuthMe200
  Errors: GetAuthMe401
}