/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Usuário autenticado
 */
export type GetAuthMe200 = any

export type GetAuthMeQueryResponse = GetAuthMe200

export type GetAuthMeQuery = {
  Response: GetAuthMe200
  Errors: any
}