/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Certificate } from './Certificate'

export type GetCertificatesIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string
}

/**
 * @description Certificate found
 */
export type GetCertificatesId200 = Certificate

export type GetCertificatesIdQueryResponse = GetCertificatesId200

export type GetCertificatesIdQuery = {
  Response: GetCertificatesId200
  PathParams: GetCertificatesIdPathParams
  Errors: any
}