/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Lista de empresas
 */
export type GetCompany200 = any

export type GetCompanyQueryResponse = GetCompany200

export type GetCompanyQuery = {
  Response: GetCompany200
  Errors: any
}