/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Certificate } from './Certificate.ts'

export type GetCertificatesIdPathParams = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description Certificado
 */
export type GetCertificatesId200 = Certificate

export type GetCertificatesIdQueryResponse = GetCertificatesId200

export type GetCertificatesIdQuery = {
  Response: GetCertificatesId200
  PathParams: GetCertificatesIdPathParams
  Errors: any
}