/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetCertificatesTitlePathParams = {
  /**
   * @type string
   */
  title: string
}

/**
 * @description Certificado
 */
export type GetCertificatesTitle200 = any

export type GetCertificatesTitleQueryResponse = GetCertificatesTitle200

export type GetCertificatesTitleTitleQuery = {
  Response: GetCertificatesTitle200
  PathParams: GetCertificatesTitlePathParams
  Errors: any
}