/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetCompanyIdPathParams = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description Empresa
 */
export type GetCompanyId200 = any

export type GetCompanyIdQueryResponse = GetCompanyId200

export type GetCompanyIdQuery = {
  Response: GetCompanyId200
  PathParams: GetCompanyIdPathParams
  Errors: any
}