/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetCompanyNamePathParams = {
  /**
   * @type string
   */
  name: string
}

/**
 * @description Empresa
 */
export type GetCompanyName200 = any

export type GetCompanyNameQueryResponse = GetCompanyName200

export type GetCompanyNameNameQuery = {
  Response: GetCompanyName200
  PathParams: GetCompanyNamePathParams
  Errors: any
}