/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Certificate } from './Certificate.ts'

/**
 * @description Lista de certificados
 */
export type GetCertificates200 = Certificate[]

export type GetCertificatesQueryResponse = GetCertificates200

export type GetCertificatesQuery = {
  Response: GetCertificates200
  Errors: any
}