/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Link } from './Link'

export type GetLinksIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string
}

/**
 * @description Link found
 */
export type GetLinksId200 = Link

export type GetLinksIdQueryResponse = GetLinksId200

export type GetLinksIdQuery = {
  Response: GetLinksId200
  PathParams: GetLinksIdPathParams
  Errors: any
}