/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Link } from './Link'

export type GetLinksQueryParams = {
  /**
   * @default 1
   * @type integer | undefined
   */
  page?: number
  /**
   * @default 10
   * @type integer | undefined
   */
  limit?: number
}

/**
 * @description A paginated list of links
 */
export type GetLinks200 = {
  /**
   * @type array | undefined
   */
  data?: Link[]
  /**
   * @type integer | undefined
   */
  page?: number
  /**
   * @type integer | undefined
   */
  limit?: number
  /**
   * @type boolean | undefined
   */
  next?: boolean
}

export type GetLinksQueryResponse = GetLinks200

export type GetLinksQuery = {
  Response: GetLinks200
  QueryParams: GetLinksQueryParams
  Errors: any
}