/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Owner } from './Owner'

export type GetOwnersQueryParams = {
  /**
   * @default 1
   * @type integer | undefined
   */
  page?: number
  /**
   * @default 10
   * @type integer | undefined
   */
  limit?: number
}

/**
 * @description A paginated list of owners
 */
export type GetOwners200 = {
  /**
   * @type array | undefined
   */
  data?: Owner[]
  /**
   * @type integer | undefined
   */
  page?: number
  /**
   * @type integer | undefined
   */
  limit?: number
  /**
   * @type boolean | undefined
   */
  next?: boolean
}

export type GetOwnersQueryResponse = GetOwners200

export type GetOwnersQuery = {
  Response: GetOwners200
  QueryParams: GetOwnersQueryParams
  Errors: any
}