/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Owner } from './Owner'

export type GetOwnersIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string
}

/**
 * @description Owner found
 */
export type GetOwnersId200 = Owner

export type GetOwnersIdQueryResponse = GetOwnersId200

export type GetOwnersIdQuery = {
  Response: GetOwnersId200
  PathParams: GetOwnersIdPathParams
  Errors: any
}