/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Lista de projetos
 */
export type GetProject200 = any

export type GetProjectQueryResponse = GetProject200

export type GetProjectQuery = {
  Response: GetProject200
  Errors: any
}