/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetProjectIdPathParams = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description Projeto
 */
export type GetProjectId200 = any

export type GetProjectIdQueryResponse = GetProjectId200

export type GetProjectIdQuery = {
  Response: GetProjectId200
  PathParams: GetProjectIdPathParams
  Errors: any
}