/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetProjectSlugPathParams = {
  /**
   * @type string
   */
  slug: string
}

/**
 * @description Projeto
 */
export type GetProjectSlug200 = any

export type GetProjectSlugQueryResponse = GetProjectSlug200

export type GetProjectSlugSlugQuery = {
  Response: GetProjectSlug200
  PathParams: GetProjectSlugPathParams
  Errors: any
}