/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from './User'

export type GetUsersIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string
}

/**
 * @description User found
 */
export type GetUsersId200 = User

export type GetUsersIdQueryResponse = GetUsersId200

export type GetUsersIdQuery = {
  Response: GetUsersId200
  PathParams: GetUsersIdPathParams
  Errors: any
}