/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from './User'

export type GetUsersUsernamePathParams = {
  /**
   * @type string
   */
  username: string
}

/**
 * @description User found
 */
export type GetUsersUsername200 = User

export type GetUsersUsernameQueryResponse = GetUsersUsername200

export type GetUsersUsernameUsernameQuery = {
  Response: GetUsersUsername200
  PathParams: GetUsersUsernamePathParams
  Errors: any
}