/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from './User.ts'

/**
 * @description Lista de usuários
 */
export type GetUser200 = User[]

export type GetUserQueryResponse = GetUser200

export type GetUserQuery = {
  Response: GetUser200
  Errors: any
}