/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from './User'

export type GetUsersQueryParams = {
  /**
   * @default 1
   * @type integer | undefined
   */
  page?: number
  /**
   * @default 10
   * @type integer | undefined
   */
  limit?: number
}

/**
 * @description A paginated list of users
 */
export type GetUsers200 = {
  /**
   * @type array | undefined
   */
  data?: User[]
  /**
   * @type integer | undefined
   */
  page?: number
  /**
   * @type integer | undefined
   */
  limit?: number
  /**
   * @type boolean | undefined
   */
  next?: boolean
}

export type GetUsersQueryResponse = GetUsers200

export type GetUsersQuery = {
  Response: GetUsers200
  QueryParams: GetUsersQueryParams
  Errors: any
}