/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type LoginAuthDTO = {
  /**
   * @type string, email
   */
  email: string
  /**
   * @type string
   */
  password: string
}