/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Owner = {
  /**
   * @type string | undefined, uuid
   */
  id?: string
  /**
   * @type string | undefined
   */
  name?: string
  /**
   * @type string | undefined, email
   */
  email?: string
  /**
   * @type string | undefined
   */
  phone?: string
  /**
   * @type string | undefined, date-time
   */
  createdAt?: string
  /**
   * @type string | undefined, date-time
   */
  updatedAt?: string
}