/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateCertificateDto } from './CreateCertificateDto.ts'

export type PatchCertificatesIdPathParams = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description Certificado atualizado
 */
export type PatchCertificatesId200 = any

export type PatchCertificatesIdMutationRequest = CreateCertificateDto

export type PatchCertificatesIdMutationResponse = PatchCertificatesId200

export type PatchCertificatesIdMutation = {
  Response: PatchCertificatesId200
  Request: PatchCertificatesIdMutationRequest
  PathParams: PatchCertificatesIdPathParams
  Errors: any
}