/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Link } from './Link'
import type { UpdateLinkDto } from './UpdateLinkDto'

export type PatchLinksIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string
}

/**
 * @description Link updated
 */
export type PatchLinksId200 = Link

export type PatchLinksIdMutationRequest = UpdateLinkDto

export type PatchLinksIdMutationResponse = PatchLinksId200

export type PatchLinksIdMutation = {
  Response: PatchLinksId200
  Request: PatchLinksIdMutationRequest
  PathParams: PatchLinksIdPathParams
  Errors: any
}