/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateUserDto } from './CreateUserDto.ts'
import type { User } from './User.ts'

export type PatchUserIdPathParams = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description Usuário atualizado
 */
export type PatchUserId200 = User

export type PatchUserIdMutationRequest = CreateUserDto

export type PatchUserIdMutationResponse = PatchUserId200

export type PatchUserIdMutation = {
  Response: PatchUserId200
  Request: PatchUserIdMutationRequest
  PathParams: PatchUserIdPathParams
  Errors: any
}