/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Certificate } from './Certificate'
import type { UpdateCertificateDto } from './UpdateCertificateDto'

export type PatchCertificatesIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string
}

/**
 * @description Certificate updated
 */
export type PatchCertificatesId200 = Certificate

export type PatchCertificatesIdMutationRequest = UpdateCertificateDto

export type PatchCertificatesIdMutationResponse = PatchCertificatesId200

export type PatchCertificatesIdMutation = {
  Response: PatchCertificatesId200
  Request: PatchCertificatesIdMutationRequest
  PathParams: PatchCertificatesIdPathParams
  Errors: any
}