/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateCompanyDto } from './CreateCompanyDto.ts'

export type PatchCompanyIdPathParams = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description Empresa atualizada
 */
export type PatchCompanyId200 = any

export type PatchCompanyIdMutationRequest = CreateCompanyDto

export type PatchCompanyIdMutationResponse = PatchCompanyId200

export type PatchCompanyIdMutation = {
  Response: PatchCompanyId200
  Request: PatchCompanyIdMutationRequest
  PathParams: PatchCompanyIdPathParams
  Errors: any
}