/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UpdateUserDto } from './UpdateUserDto'
import type { User } from './User'

export type PatchUsersIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string
}

/**
 * @description User updated
 */
export type PatchUsersId200 = User

export type PatchUsersIdMutationRequest = UpdateUserDto

export type PatchUsersIdMutationResponse = PatchUsersId200

export type PatchUsersIdMutation = {
  Response: PatchUsersId200
  Request: PatchUsersIdMutationRequest
  PathParams: PatchUsersIdPathParams
  Errors: any
}