/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Owner } from './Owner'
import type { UpdateOwnerDto } from './UpdateOwnerDto'

export type PatchOwnersIdPathParams = {
  /**
   * @type string, uuid
   */
  id: string
}

/**
 * @description Owner updated
 */
export type PatchOwnersId200 = Owner

export type PatchOwnersIdMutationRequest = UpdateOwnerDto

export type PatchOwnersIdMutationResponse = PatchOwnersId200

export type PatchOwnersIdMutation = {
  Response: PatchOwnersId200
  Request: PatchOwnersIdMutationRequest
  PathParams: PatchOwnersIdPathParams
  Errors: any
}