/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateProjectDto } from './CreateProjectDto.ts'

export type PatchProjectIdPathParams = {
  /**
   * @type string
   */
  id: string
}

/**
 * @description Projeto atualizado
 */
export type PatchProjectId200 = any

export type PatchProjectIdMutationRequest = CreateProjectDto

export type PatchProjectIdMutationResponse = PatchProjectId200

export type PatchProjectIdMutation = {
  Response: PatchProjectId200
  Request: PatchProjectIdMutationRequest
  PathParams: PatchProjectIdPathParams
  Errors: any
}