/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateUserDto } from './CreateUserDto'
import type { User } from './User'

/**
 * @description User created
 */
export type PostUsers201 = User

export type PostUsersMutationRequest = CreateUserDto

export type PostUsersMutationResponse = PostUsers201

export type PostUsersMutation = {
  Response: PostUsers201
  Request: PostUsersMutationRequest
  Errors: any
}