/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateUserDto } from './CreateUserDto.ts'
import type { User } from './User.ts'

/**
 * @description Usuário criado
 */
export type PostUser200 = User

export type PostUserMutationRequest = CreateUserDto

export type PostUserMutationResponse = PostUser200

export type PostUserMutation = {
  Response: PostUser200
  Request: PostUserMutationRequest
  Errors: any
}