/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Certificate } from './Certificate.ts'
import type { CreateCertificateDto } from './CreateCertificateDto.ts'

/**
 * @description Certificado criado
 */
export type PostCertificates200 = Certificate

export type PostCertificatesMutationRequest = CreateCertificateDto

export type PostCertificatesMutationResponse = PostCertificates200

export type PostCertificatesMutation = {
  Response: PostCertificates200
  Request: PostCertificatesMutationRequest
  Errors: any
}