/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateProjectDto } from './CreateProjectDto.ts'

/**
 * @description Projeto criado
 */
export type PostProject200 = any

export type PostProjectMutationRequest = {
  /**
   * @type string | undefined, binary
   */
  cover?: Blob
  /**
   * @type string | undefined, binary
   */
  photo?: Blob
  /**
   * @type array | undefined
   */
  images?: Blob[]
  /**
   * @type object | undefined
   */
  data?: CreateProjectDto
}

export type PostProjectMutationResponse = PostProject200

export type PostProjectMutation = {
  Response: PostProject200
  Request: PostProjectMutationRequest
  Errors: any
}