/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateCompanyDto } from './CreateCompanyDto.ts'
import type { CreateLinksDto } from './CreateLinksDto.ts'

/**
 * @description Empresa criada
 */
export type PostCompany200 = any

export type PostCompanyMutationRequest = {
  /**
   * @type string | undefined, binary
   */
  image?: Blob
  /**
   * @type object | undefined
   */
  company?: CreateCompanyDto
  /**
   * @type object | undefined
   */
  links?: CreateLinksDto
}

export type PostCompanyMutationResponse = PostCompany200

export type PostCompanyMutation = {
  Response: PostCompany200
  Request: PostCompanyMutationRequest
  Errors: any
}