/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateProjectDto } from './CreateProjectDto'
import type { Project } from './Project'

/**
 * @description Project created
 */
export type PostProjects201 = Project

export type PostProjectsMutationRequest = CreateProjectDto & {
  /**
   * @type string | undefined, binary
   */
  cover?: Blob
  /**
   * @type string | undefined, binary
   */
  photo?: Blob
  /**
   * @type array | undefined
   */
  images?: Blob[]
}

export type PostProjectsMutationResponse = PostProjects201

export type PostProjectsMutation = {
  Response: PostProjects201
  Request: PostProjectsMutationRequest
  Errors: any
}