/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { LoginAuthDTO } from './LoginAuthDTO.ts'

/**
 * @description Token JWT e usuário
 */
export type PostAuthLogin200 = any

export type PostAuthLoginMutationRequest = LoginAuthDTO

export type PostAuthLoginMutationResponse = PostAuthLogin200

export type PostAuthLoginMutation = {
  Response: PostAuthLogin200
  Request: PostAuthLoginMutationRequest
  Errors: any
}