/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Attach } from './Attach'

/**
 * @description File uploaded
 */
export type PostAttachesUpload201 = Attach

export type PostAttachesUploadMutationRequest = {
  /**
   * @type string | undefined, binary
   */
  file?: Blob
}

export type PostAttachesUploadMutationResponse = PostAttachesUpload201

export type PostAttachesUploadMutation = {
  Response: PostAttachesUpload201
  Request: PostAttachesUploadMutationRequest
  Errors: any
}