/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AuthResult } from './AuthResult'
import type { LoginAuthDTO } from './LoginAuthDTO'

/**
 * @description Successful authentication
 */
export type PostAuthLogin200 = AuthResult

/**
 * @description Unauthorized
 */
export type PostAuthLogin401 = any

export type PostAuthLoginMutationRequest = LoginAuthDTO

export type PostAuthLoginMutationResponse = PostAuthLogin200

export type PostAuthLoginMutation = {
  Response: PostAuthLogin200
  Request: PostAuthLoginMutationRequest
  Errors: PostAuthLogin401
}