/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Certificate } from './Certificate'
import type { CreateCertificateDto } from './CreateCertificateDto'

/**
 * @description Certificate created
 */
export type PostCertificates201 = Certificate

export type PostCertificatesMutationRequest = CreateCertificateDto

export type PostCertificatesMutationResponse = PostCertificates201

export type PostCertificatesMutation = {
  Response: PostCertificates201
  Request: PostCertificatesMutationRequest
  Errors: any
}