/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Company } from './Company'
import type { CreateCompanyDto } from './CreateCompanyDto'

/**
 * @description Company created
 */
export type PostCompanies201 = Company

export type PostCompaniesMutationRequest = CreateCompanyDto & {
  /**
   * @type string | undefined, binary
   */
  photo?: Blob
}

export type PostCompaniesMutationResponse = PostCompanies201

export type PostCompaniesMutation = {
  Response: PostCompanies201
  Request: PostCompaniesMutationRequest
  Errors: any
}