/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateLinkDto } from './CreateLinkDto'
import type { Link } from './Link'

/**
 * @description Link created
 */
export type PostLinks201 = Link

export type PostLinksMutationRequest = CreateLinkDto

export type PostLinksMutationResponse = PostLinks201

export type PostLinksMutation = {
  Response: PostLinks201
  Request: PostLinksMutationRequest
  Errors: any
}