/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreateOwnerDto } from './CreateOwnerDto'
import type { Owner } from './Owner'

/**
 * @description Owner created
 */
export type PostOwners201 = Owner

export type PostOwnersMutationRequest = CreateOwnerDto

export type PostOwnersMutationResponse = PostOwners201

export type PostOwnersMutation = {
  Response: PostOwners201
  Request: PostOwnersMutationRequest
  Errors: any
}