/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateCertificateDto = {
  /**
   * @type string | undefined
   */
  title?: string
  /**
   * @type string | undefined
   */
  description?: string
  /**
   * @type string | undefined
   */
  platform?: string
  /**
   * @type string | undefined, uri
   */
  url?: string
  /**
   * @type integer | undefined
   */
  workload?: number
}