/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const updateUserDtoRoleEnum = {
  owner: 'owner',
  commun: 'commun',
} as const

export type UpdateUserDtoRoleEnum = (typeof updateUserDtoRoleEnum)[keyof typeof updateUserDtoRoleEnum]

export type UpdateUserDto = {
  /**
   * @type string | undefined
   */
  username?: string
  /**
   * @type string | undefined
   */
  name?: string
  /**
   * @type string | undefined
   */
  password?: string
  /**
   * @type string | undefined, email
   */
  email?: string
  /**
   * @type string | undefined
   */
  role?: UpdateUserDtoRoleEnum
}