/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateOwnerDto = {
  /**
   * @type string | undefined
   */
  name?: string
  /**
   * @type string | undefined, email
   */
  email?: string
  /**
   * @type string | undefined
   */
  phone?: string
}