/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type UpdateLinkDto = {
  /**
   * @type string | undefined, uri
   */
  github?: string
  /**
   * @type string | undefined, uri
   */
  figma?: string
  /**
   * @type string | undefined, uri
   */
  publicUrl?: string
}