/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type User = {
  /**
   * @type string | undefined
   */
  id?: string
  /**
   * @type string | undefined
   */
  username?: string
  /**
   * @type string | undefined
   */
  name?: string
  /**
   * @type string | undefined
   */
  email?: string
  /**
   * @type string | undefined
   */
  role?: string
  /**
   * @type string | undefined, date-time
   */
  createdAt?: string
  /**
   * @type string | undefined, date-time
   */
  updatedAt?: string
}