/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const userRoleEnum = {
  owner: 'owner',
  commun: 'commun',
} as const

export type UserRoleEnum = (typeof userRoleEnum)[keyof typeof userRoleEnum]

export type User = {
  /**
   * @type string | undefined, uuid
   */
  id?: string
  /**
   * @type string | undefined
   */
  username?: string
  /**
   * @type string | undefined
   */
  name?: string
  /**
   * @type string | undefined, email
   */
  email?: string
  /**
   * @type string | undefined
   */
  role?: UserRoleEnum
  /**
   * @type string | undefined, date-time
   */
  createdAt?: string
  /**
   * @type string | undefined, date-time
   */
  updatedAt?: string
}