/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { userSchema } from './userSchema'
import { z } from 'zod'

export const authResultSchema = z.object({
  access: z.string().optional(),
  user: z.lazy(() => userSchema).optional(),
})