/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createLinksDtoSchema } from './createLinksDtoSchema.ts'
import { z } from 'zod'

export const createProjectDtoSchema = z.object({
  name: z.string(),
  slug: z.string(),
  shortDescription: z.string(),
  description: z.string(),
  skills: z.array(z.string()),
  companyId: z.string().optional(),
  links: z.lazy(() => createLinksDtoSchema),
})