/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const createCertificateDtoSchema = z.object({
  title: z.string(),
  description: z.string(),
  platform: z.string(),
  url: z.string(),
  workload: z.number().int(),
})