/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createLinkDtoSchema } from './createLinkDtoSchema'
import { z } from 'zod'

export const createProjectDtoSchema = z.object({
  name: z.string(),
  shortDescription: z.string(),
  description: z.string(),
  skills: z.array(z.string()),
  links: z.lazy(() => createLinkDtoSchema),
  companyId: z.string().uuid().optional(),
})