/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const createUserDtoSchema = z.object({
  username: z.string(),
  name: z.string(),
  password: z.string(),
  email: z.string().optional(),
  role: z.string(),
})