/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const createOwnerDtoSchema = z.object({
  name: z.string(),
  email: z.string().email(),
  phone: z.string(),
})