/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const createLinkDtoSchema = z.object({
  github: z.string().url(),
  figma: z.string().url(),
  publicUrl: z.string().url(),
})