/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const deleteUserIdPathParamsSchema = z.object({
  id: z.string(),
})

/**
 * @description Usuário deletado
 */
export const deleteUserId200Schema = z.any()

export const deleteUserIdMutationResponseSchema = z.lazy(() => deleteUserId200Schema)