/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const deleteOwnersIdPathParamsSchema = z.object({
  id: z.string().uuid(),
})

/**
 * @description Owner deleted
 */
export const deleteOwnersId200Schema = z.any()

export const deleteOwnersIdMutationResponseSchema = z.lazy(() => deleteOwnersId200Schema)