/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const deleteLinksIdPathParamsSchema = z.object({
  id: z.string().uuid(),
})

/**
 * @description Link deleted
 */
export const deleteLinksId200Schema = z.any()

export const deleteLinksIdMutationResponseSchema = z.lazy(() => deleteLinksId200Schema)