/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const deleteCompanyIdPathParamsSchema = z.object({
  id: z.string(),
})

/**
 * @description Empresa deletada
 */
export const deleteCompanyId200Schema = z.any()

export const deleteCompanyIdMutationResponseSchema = z.lazy(() => deleteCompanyId200Schema)