/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const deleteProjectIdPathParamsSchema = z.object({
  id: z.string(),
})

/**
 * @description Projeto deletado
 */
export const deleteProjectId200Schema = z.any()

export const deleteProjectIdMutationResponseSchema = z.lazy(() => deleteProjectId200Schema)