/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const deleteUsersIdPathParamsSchema = z.object({
  id: z.string().uuid(),
})

/**
 * @description User deleted
 */
export const deleteUsersId200Schema = z.any()

export const deleteUsersIdMutationResponseSchema = z.lazy(() => deleteUsersId200Schema)