/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const deleteCertificatesIdPathParamsSchema = z.object({
  id: z.string(),
})

/**
 * @description Certificado deletado
 */
export const deleteCertificatesId200Schema = z.any()

export const deleteCertificatesIdMutationResponseSchema = z.lazy(() => deleteCertificatesId200Schema)