/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { userSchema } from './userSchema'
import { z } from 'zod'

/**
 * @description User info
 */
export const getAuthMe200Schema = z.lazy(() => userSchema)

/**
 * @description Unauthorized
 */
export const getAuthMe401Schema = z.any()

export const getAuthMeQueryResponseSchema = z.lazy(() => getAuthMe200Schema)