/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { certificateSchema } from './certificateSchema'
import { z } from 'zod'

export const getCertificatesIdPathParamsSchema = z.object({
  id: z.string().uuid(),
})

/**
 * @description Certificate found
 */
export const getCertificatesId200Schema = z.lazy(() => certificateSchema)

export const getCertificatesIdQueryResponseSchema = z.lazy(() => getCertificatesId200Schema)