/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { certificateSchema } from './certificateSchema'
import { z } from 'zod'

export const getCertificatesQueryParamsSchema = z.object({
  page: z.coerce.number().int().default(1),
  limit: z.coerce.number().int().default(10),
})

/**
 * @description A paginated list of certificates
 */
export const getCertificates200Schema = z.object({
  data: z.array(z.lazy(() => certificateSchema)).optional(),
  page: z.number().int().optional(),
  limit: z.number().int().optional(),
  next: z.boolean().optional(),
})

export const getCertificatesQueryResponseSchema = z.lazy(() => getCertificates200Schema)