/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const getCompanyIdPathParamsSchema = z.object({
  id: z.string(),
})

/**
 * @description Empresa
 */
export const getCompanyId200Schema = z.any()

export const getCompanyIdQueryResponseSchema = z.lazy(() => getCompanyId200Schema)