/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const getCertificatesTitlePathParamsSchema = z.object({
  title: z.string(),
})

/**
 * @description Certificado
 */
export const getCertificatesTitle200Schema = z.any()

export const getCertificatesTitleQueryResponseSchema = z.lazy(() => getCertificatesTitle200Schema)