/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { certificateSchema } from './certificateSchema.ts'
import { z } from 'zod'

/**
 * @description Lista de certificados
 */
export const getCertificates200Schema = z.array(z.lazy(() => certificateSchema))

export const getCertificatesQueryResponseSchema = z.lazy(() => getCertificates200Schema)