/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

/**
 * @description Lista de empresas
 */
export const getCompany200Schema = z.any()

export const getCompanyQueryResponseSchema = z.lazy(() => getCompany200Schema)