/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { linkSchema } from './linkSchema'
import { z } from 'zod'

export const getLinksIdPathParamsSchema = z.object({
  id: z.string().uuid(),
})

/**
 * @description Link found
 */
export const getLinksId200Schema = z.lazy(() => linkSchema)

export const getLinksIdQueryResponseSchema = z.lazy(() => getLinksId200Schema)