/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { linkSchema } from './linkSchema'
import { z } from 'zod'

export const getLinksQueryParamsSchema = z.object({
  page: z.coerce.number().int().default(1),
  limit: z.coerce.number().int().default(10),
})

/**
 * @description A paginated list of links
 */
export const getLinks200Schema = z.object({
  data: z.array(z.lazy(() => linkSchema)).optional(),
  page: z.number().int().optional(),
  limit: z.number().int().optional(),
  next: z.boolean().optional(),
})

export const getLinksQueryResponseSchema = z.lazy(() => getLinks200Schema)