/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { ownerSchema } from './ownerSchema'
import { z } from 'zod'

export const getOwnersQueryParamsSchema = z.object({
  page: z.coerce.number().int().default(1),
  limit: z.coerce.number().int().default(10),
})

/**
 * @description A paginated list of owners
 */
export const getOwners200Schema = z.object({
  data: z.array(z.lazy(() => ownerSchema)).optional(),
  page: z.number().int().optional(),
  limit: z.number().int().optional(),
  next: z.boolean().optional(),
})

export const getOwnersQueryResponseSchema = z.lazy(() => getOwners200Schema)