/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { ownerSchema } from './ownerSchema'
import { z } from 'zod'

export const getOwnersIdPathParamsSchema = z.object({
  id: z.string().uuid(),
})

/**
 * @description Owner found
 */
export const getOwnersId200Schema = z.lazy(() => ownerSchema)

export const getOwnersIdQueryResponseSchema = z.lazy(() => getOwnersId200Schema)