/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

/**
 * @description Lista de projetos
 */
export const getProject200Schema = z.any()

export const getProjectQueryResponseSchema = z.lazy(() => getProject200Schema)