/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { userSchema } from './userSchema.ts'
import { z } from 'zod'

export const getUserIdPathParamsSchema = z.object({
  id: z.string(),
})

/**
 * @description Usuário
 */
export const getUserId200Schema = z.lazy(() => userSchema)

export const getUserIdQueryResponseSchema = z.lazy(() => getUserId200Schema)