/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { userSchema } from './userSchema'
import { z } from 'zod'

export const getUsersIdPathParamsSchema = z.object({
  id: z.string().uuid(),
})

/**
 * @description User found
 */
export const getUsersId200Schema = z.lazy(() => userSchema)

export const getUsersIdQueryResponseSchema = z.lazy(() => getUsersId200Schema)