/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { userSchema } from './userSchema.ts'
import { z } from 'zod'

/**
 * @description Lista de usuários
 */
export const getUser200Schema = z.array(z.lazy(() => userSchema))

export const getUserQueryResponseSchema = z.lazy(() => getUser200Schema)