/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { userSchema } from './userSchema'
import { z } from 'zod'

export const getUsersQueryParamsSchema = z.object({
  page: z.coerce.number().int().default(1),
  limit: z.coerce.number().int().default(10),
})

/**
 * @description A paginated list of users
 */
export const getUsers200Schema = z.object({
  data: z.array(z.lazy(() => userSchema)).optional(),
  page: z.number().int().optional(),
  limit: z.number().int().optional(),
  next: z.boolean().optional(),
})

export const getUsersQueryResponseSchema = z.lazy(() => getUsers200Schema)