/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { userSchema } from './userSchema'
import { z } from 'zod'

export const getUsersUsernamePathParamsSchema = z.object({
  username: z.string(),
})

/**
 * @description User found
 */
export const getUsersUsername200Schema = z.lazy(() => userSchema)

export const getUsersUsernameQueryResponseSchema = z.lazy(() => getUsersUsername200Schema)