/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const linkSchema = z.object({
  id: z.string().uuid().optional(),
  github: z.string().url().optional(),
  figma: z.string().url().optional(),
  publicUrl: z.string().url().optional(),
  createdAt: z.string().datetime().optional(),
  updatedAt: z.string().datetime().optional(),
})