/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { updateUserDtoSchema } from './updateUserDtoSchema'
import { userSchema } from './userSchema'
import { z } from 'zod'

export const patchUsersIdPathParamsSchema = z.object({
  id: z.string().uuid(),
})

/**
 * @description User updated
 */
export const patchUsersId200Schema = z.lazy(() => userSchema)

export const patchUsersIdMutationRequestSchema = z.lazy(() => updateUserDtoSchema)

export const patchUsersIdMutationResponseSchema = z.lazy(() => patchUsersId200Schema)