/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { ownerSchema } from './ownerSchema'
import { updateOwnerDtoSchema } from './updateOwnerDtoSchema'
import { z } from 'zod'

export const patchOwnersIdPathParamsSchema = z.object({
  id: z.string().uuid(),
})

/**
 * @description Owner updated
 */
export const patchOwnersId200Schema = z.lazy(() => ownerSchema)

export const patchOwnersIdMutationRequestSchema = z.lazy(() => updateOwnerDtoSchema)

export const patchOwnersIdMutationResponseSchema = z.lazy(() => patchOwnersId200Schema)