/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { linkSchema } from './linkSchema'
import { updateLinkDtoSchema } from './updateLinkDtoSchema'
import { z } from 'zod'

export const patchLinksIdPathParamsSchema = z.object({
  id: z.string().uuid(),
})

/**
 * @description Link updated
 */
export const patchLinksId200Schema = z.lazy(() => linkSchema)

export const patchLinksIdMutationRequestSchema = z.lazy(() => updateLinkDtoSchema)

export const patchLinksIdMutationResponseSchema = z.lazy(() => patchLinksId200Schema)