/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { certificateSchema } from './certificateSchema'
import { updateCertificateDtoSchema } from './updateCertificateDtoSchema'
import { z } from 'zod'

export const patchCertificatesIdPathParamsSchema = z.object({
  id: z.string().uuid(),
})

/**
 * @description Certificate updated
 */
export const patchCertificatesId200Schema = z.lazy(() => certificateSchema)

export const patchCertificatesIdMutationRequestSchema = z.lazy(() => updateCertificateDtoSchema)

export const patchCertificatesIdMutationResponseSchema = z.lazy(() => patchCertificatesId200Schema)