/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createUserDtoSchema } from './createUserDtoSchema.ts'
import { userSchema } from './userSchema.ts'
import { z } from 'zod'

export const patchUserIdPathParamsSchema = z.object({
  id: z.string(),
})

/**
 * @description Usuário atualizado
 */
export const patchUserId200Schema = z.lazy(() => userSchema)

export const patchUserIdMutationRequestSchema = z.lazy(() => createUserDtoSchema)

export const patchUserIdMutationResponseSchema = z.lazy(() => patchUserId200Schema)