/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createProjectDtoSchema } from './createProjectDtoSchema.ts'
import { z } from 'zod'

export const patchProjectIdPathParamsSchema = z.object({
  id: z.string(),
})

/**
 * @description Projeto atualizado
 */
export const patchProjectId200Schema = z.any()

export const patchProjectIdMutationRequestSchema = z.lazy(() => createProjectDtoSchema)

export const patchProjectIdMutationResponseSchema = z.lazy(() => patchProjectId200Schema)