/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createCertificateDtoSchema } from './createCertificateDtoSchema.ts'
import { z } from 'zod'

export const patchCertificatesIdPathParamsSchema = z.object({
  id: z.string(),
})

/**
 * @description Certificado atualizado
 */
export const patchCertificatesId200Schema = z.any()

export const patchCertificatesIdMutationRequestSchema = z.lazy(() => createCertificateDtoSchema)

export const patchCertificatesIdMutationResponseSchema = z.lazy(() => patchCertificatesId200Schema)