/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { certificateSchema } from './certificateSchema.ts'
import { createCertificateDtoSchema } from './createCertificateDtoSchema.ts'
import { z } from 'zod'

/**
 * @description Certificado criado
 */
export const postCertificates200Schema = z.lazy(() => certificateSchema)

export const postCertificatesMutationRequestSchema = z.lazy(() => createCertificateDtoSchema)

export const postCertificatesMutationResponseSchema = z.lazy(() => postCertificates200Schema)