/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { authResultSchema } from './authResultSchema'
import { loginAuthDTOSchema } from './loginAuthDTOSchema'
import { z } from 'zod'

/**
 * @description Successful authentication
 */
export const postAuthLogin200Schema = z.lazy(() => authResultSchema)

/**
 * @description Unauthorized
 */
export const postAuthLogin401Schema = z.any()

export const postAuthLoginMutationRequestSchema = z.lazy(() => loginAuthDTOSchema)

export const postAuthLoginMutationResponseSchema = z.lazy(() => postAuthLogin200Schema)