/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { loginAuthDTOSchema } from './loginAuthDTOSchema.ts'
import { z } from 'zod'

/**
 * @description Token JWT e usuário
 */
export const postAuthLogin200Schema = z.any()

export const postAuthLoginMutationRequestSchema = z.lazy(() => loginAuthDTOSchema)

export const postAuthLoginMutationResponseSchema = z.lazy(() => postAuthLogin200Schema)