/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createUserDtoSchema } from './createUserDtoSchema'
import { userSchema } from './userSchema'
import { z } from 'zod'

/**
 * @description User created
 */
export const postUsers201Schema = z.lazy(() => userSchema)

export const postUsersMutationRequestSchema = z.lazy(() => createUserDtoSchema)

export const postUsersMutationResponseSchema = z.lazy(() => postUsers201Schema)