/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { certificateSchema } from './certificateSchema'
import { createCertificateDtoSchema } from './createCertificateDtoSchema'
import { z } from 'zod'

/**
 * @description Certificate created
 */
export const postCertificates201Schema = z.lazy(() => certificateSchema)

export const postCertificatesMutationRequestSchema = z.lazy(() => createCertificateDtoSchema)

export const postCertificatesMutationResponseSchema = z.lazy(() => postCertificates201Schema)