/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createLinkDtoSchema } from './createLinkDtoSchema'
import { linkSchema } from './linkSchema'
import { z } from 'zod'

/**
 * @description Link created
 */
export const postLinks201Schema = z.lazy(() => linkSchema)

export const postLinksMutationRequestSchema = z.lazy(() => createLinkDtoSchema)

export const postLinksMutationResponseSchema = z.lazy(() => postLinks201Schema)