/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createOwnerDtoSchema } from './createOwnerDtoSchema'
import { ownerSchema } from './ownerSchema'
import { z } from 'zod'

/**
 * @description Owner created
 */
export const postOwners201Schema = z.lazy(() => ownerSchema)

export const postOwnersMutationRequestSchema = z.lazy(() => createOwnerDtoSchema)

export const postOwnersMutationResponseSchema = z.lazy(() => postOwners201Schema)