/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { companySchema } from './companySchema'
import { createCompanyDtoSchema } from './createCompanyDtoSchema'
import { z } from 'zod'

/**
 * @description Company created
 */
export const postCompanies201Schema = z.lazy(() => companySchema)

export const postCompaniesMutationRequestSchema = z
  .lazy(() => createCompanyDtoSchema)
  .and(
    z.object({
      photo: z.instanceof(File).optional(),
    }),
  )

export const postCompaniesMutationResponseSchema = z.lazy(() => postCompanies201Schema)