/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createProjectDtoSchema } from './createProjectDtoSchema'
import { projectSchema } from './projectSchema'
import { z } from 'zod'

/**
 * @description Project created
 */
export const postProjects201Schema = z.lazy(() => projectSchema)

export const postProjectsMutationRequestSchema = z
  .lazy(() => createProjectDtoSchema)
  .and(
    z.object({
      cover: z.instanceof(File).optional(),
      photo: z.instanceof(File).optional(),
      images: z.array(z.instanceof(File)).optional(),
    }),
  )

export const postProjectsMutationResponseSchema = z.lazy(() => postProjects201Schema)