/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createProjectDtoSchema } from './createProjectDtoSchema.ts'
import { z } from 'zod'

/**
 * @description Projeto criado
 */
export const postProject200Schema = z.any()

export const postProjectMutationRequestSchema = z.object({
  cover: z.instanceof(File).optional(),
  photo: z.instanceof(File).optional(),
  images: z.array(z.instanceof(File)).optional(),
  data: z.lazy(() => createProjectDtoSchema).optional(),
})

export const postProjectMutationResponseSchema = z.lazy(() => postProject200Schema)