/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { attachSchema } from './attachSchema'
import { z } from 'zod'

/**
 * @description File uploaded
 */
export const postAttachesUpload201Schema = z.lazy(() => attachSchema)

export const postAttachesUploadMutationRequestSchema = z.object({
  file: z.instanceof(File).optional(),
})

export const postAttachesUploadMutationResponseSchema = z.lazy(() => postAttachesUpload201Schema)