/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createCompanyDtoSchema } from './createCompanyDtoSchema.ts'
import { createLinksDtoSchema } from './createLinksDtoSchema.ts'
import { z } from 'zod'

/**
 * @description Empresa criada
 */
export const postCompany200Schema = z.any()

export const postCompanyMutationRequestSchema = z.object({
  image: z.instanceof(File).optional(),
  company: z.lazy(() => createCompanyDtoSchema).optional(),
  links: z.lazy(() => createLinksDtoSchema).optional(),
})

export const postCompanyMutationResponseSchema = z.lazy(() => postCompany200Schema)