/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const projectSchema = z.object({
  id: z.string().uuid().optional(),
  name: z.string().optional(),
  slug: z.string().optional(),
  shortDescription: z.string().optional(),
  description: z.string().optional(),
  skills: z.array(z.string()).optional(),
  linksId: z.string().uuid().optional(),
  companyId: z.string().uuid().optional(),
  coverId: z.string().uuid().optional(),
  photoId: z.string().uuid().optional(),
  createdAt: z.string().datetime().optional(),
  updatedAt: z.string().datetime().optional(),
})