/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const updateLinkDtoSchema = z.object({
  github: z.string().url().optional(),
  figma: z.string().url().optional(),
  publicUrl: z.string().url().optional(),
})