/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const updateCertificateDtoSchema = z.object({
  title: z.string().optional(),
  description: z.string().optional(),
  platform: z.string().optional(),
  url: z.string().url().optional(),
  workload: z.number().int().optional(),
})