/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from 'zod'

export const updateUserDtoSchema = z.object({
  username: z.string().optional(),
  name: z.string().optional(),
  password: z.string().optional(),
  email: z.string().email().optional(),
  role: z.enum(['owner', 'commun']).optional(),
})