/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetOwnersQueryResponse, GetOwnersQueryParams } from '../../types/GetOwners'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getOwnersQueryKey = (params?: GetOwnersQueryParams) => [{ url: '/owners' }, ...(params ? [params] : [])] as const

export type GetOwnersQueryKey = ReturnType<typeof getOwnersQueryKey>

/**
 * @summary Get all owners with pagination
 * {@link /owners}
 */
export async function getOwners(params?: GetOwnersQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetOwnersQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/owners`, params, ...requestConfig })
  return res
}

export function getOwnersQueryOptions(params?: GetOwnersQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getOwnersQueryKey(params)
  return queryOptions<ResponseConfig<GetOwnersQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetOwnersQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getOwners(params, config)
    },
  })
}

/**
 * @summary Get all owners with pagination
 * {@link /owners}
 */
export function useGetOwners<
  TData = ResponseConfig<GetOwnersQueryResponse>,
  TQueryData = ResponseConfig<GetOwnersQueryResponse>,
  TQueryKey extends QueryKey = GetOwnersQueryKey,
>(
  params?: GetOwnersQueryParams,
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetOwnersQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getOwnersQueryKey(params)

  const query = useQuery(
    {
      ...(getOwnersQueryOptions(params, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}