/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetOwnersQueryResponse, GetOwnersQueryParams } from '../../types/GetOwners'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getOwnersInfiniteQueryKey = (params?: GetOwnersQueryParams) => [{ url: '/owners' }, ...(params ? [params] : [])] as const

export type GetOwnersInfiniteQueryKey = ReturnType<typeof getOwnersInfiniteQueryKey>

/**
 * @summary Get all owners with pagination
 * {@link /owners}
 */
export async function getOwnersInfinite(params?: GetOwnersQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetOwnersQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/owners`, params, ...requestConfig })
  return res
}

export function getOwnersInfiniteQueryOptions(params?: GetOwnersQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getOwnersInfiniteQueryKey(params)
  return infiniteQueryOptions<
    ResponseConfig<GetOwnersQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetOwnersQueryResponse>,
    typeof queryKey,
    number
  >({
    queryKey,
    queryFn: async ({ signal, pageParam }) => {
      config.signal = signal

      if (params) {
        params['next_page'] = pageParam as unknown as GetOwnersQueryParams['next_page']
      }
      return getOwnersInfinite(params, config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * @summary Get all owners with pagination
 * {@link /owners}
 */
export function useGetOwnersInfinite<
  TData = InfiniteData<ResponseConfig<GetOwnersQueryResponse>>,
  TQueryData = ResponseConfig<GetOwnersQueryResponse>,
  TQueryKey extends QueryKey = GetOwnersInfiniteQueryKey,
>(
  params?: GetOwnersQueryParams,
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetOwnersQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getOwnersInfiniteQueryKey(params)

  const query = useInfiniteQuery(
    {
      ...(getOwnersInfiniteQueryOptions(params, config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}