/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetOwnersIdQueryResponse, GetOwnersIdPathParams } from '../../types/GetOwnersId'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getOwnersIdQueryKey = (id: GetOwnersIdPathParams['id']) => [{ url: '/owners/:id', params: { id: id } }] as const

export type GetOwnersIdQueryKey = ReturnType<typeof getOwnersIdQueryKey>

/**
 * @summary Get an owner by ID
 * {@link /owners/:id}
 */
export async function getOwnersId(id: GetOwnersIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetOwnersIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/owners/${id}`, ...requestConfig })
  return res
}

export function getOwnersIdQueryOptions(id: GetOwnersIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getOwnersIdQueryKey(id)
  return queryOptions<ResponseConfig<GetOwnersIdQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetOwnersIdQueryResponse>, typeof queryKey>({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getOwnersId(id, config)
    },
  })
}

/**
 * @summary Get an owner by ID
 * {@link /owners/:id}
 */
export function useGetOwnersId<
  TData = ResponseConfig<GetOwnersIdQueryResponse>,
  TQueryData = ResponseConfig<GetOwnersIdQueryResponse>,
  TQueryKey extends QueryKey = GetOwnersIdQueryKey,
>(
  id: GetOwnersIdPathParams['id'],
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetOwnersIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getOwnersIdQueryKey(id)

  const query = useQuery(
    {
      ...(getOwnersIdQueryOptions(id, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}