/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetOwnersIdQueryResponse, GetOwnersIdPathParams } from '../../types/GetOwnersId'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getOwnersIdSuspenseQueryKey = (id: GetOwnersIdPathParams['id']) => [{ url: '/owners/:id', params: { id: id } }] as const

export type GetOwnersIdSuspenseQueryKey = ReturnType<typeof getOwnersIdSuspenseQueryKey>

/**
 * @summary Get an owner by ID
 * {@link /owners/:id}
 */
export async function getOwnersIdSuspense(id: GetOwnersIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetOwnersIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/owners/${id}`, ...requestConfig })
  return res
}

export function getOwnersIdSuspenseQueryOptions(id: GetOwnersIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getOwnersIdSuspenseQueryKey(id)
  return queryOptions<ResponseConfig<GetOwnersIdQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetOwnersIdQueryResponse>, typeof queryKey>({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getOwnersIdSuspense(id, config)
    },
  })
}

/**
 * @summary Get an owner by ID
 * {@link /owners/:id}
 */
export function useGetOwnersIdSuspense<TData = ResponseConfig<GetOwnersIdQueryResponse>, TQueryKey extends QueryKey = GetOwnersIdSuspenseQueryKey>(
  id: GetOwnersIdPathParams['id'],
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetOwnersIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getOwnersIdSuspenseQueryKey(id)

  const query = useSuspenseQuery(
    {
      ...(getOwnersIdSuspenseQueryOptions(id, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}