/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetOwnersQueryResponse, GetOwnersQueryParams } from '../../types/GetOwners'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getOwnersSuspenseQueryKey = (params?: GetOwnersQueryParams) => [{ url: '/owners' }, ...(params ? [params] : [])] as const

export type GetOwnersSuspenseQueryKey = ReturnType<typeof getOwnersSuspenseQueryKey>

/**
 * @summary Get all owners with pagination
 * {@link /owners}
 */
export async function getOwnersSuspense(params?: GetOwnersQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetOwnersQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/owners`, params, ...requestConfig })
  return res
}

export function getOwnersSuspenseQueryOptions(params?: GetOwnersQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getOwnersSuspenseQueryKey(params)
  return queryOptions<ResponseConfig<GetOwnersQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetOwnersQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getOwnersSuspense(params, config)
    },
  })
}

/**
 * @summary Get all owners with pagination
 * {@link /owners}
 */
export function useGetOwnersSuspense<TData = ResponseConfig<GetOwnersQueryResponse>, TQueryKey extends QueryKey = GetOwnersSuspenseQueryKey>(
  params?: GetOwnersQueryParams,
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetOwnersQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getOwnersSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...(getOwnersSuspenseQueryOptions(params, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}