/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetOwnersIdQueryResponse, GetOwnersIdPathParams } from '../../types/GetOwnersId'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getOwnersIdInfiniteQueryKey = (id: GetOwnersIdPathParams['id']) => [{ url: '/owners/:id', params: { id: id } }] as const

export type GetOwnersIdInfiniteQueryKey = ReturnType<typeof getOwnersIdInfiniteQueryKey>

/**
 * @summary Get an owner by ID
 * {@link /owners/:id}
 */
export async function getOwnersIdInfinite(id: GetOwnersIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetOwnersIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/owners/${id}`, ...requestConfig })
  return res
}

export function getOwnersIdInfiniteQueryOptions(id: GetOwnersIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getOwnersIdInfiniteQueryKey(id)
  return infiniteQueryOptions<ResponseConfig<GetOwnersIdQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetOwnersIdQueryResponse>, typeof queryKey>({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getOwnersIdInfinite(id, config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * @summary Get an owner by ID
 * {@link /owners/:id}
 */
export function useGetOwnersIdInfinite<
  TData = InfiniteData<ResponseConfig<GetOwnersIdQueryResponse>>,
  TQueryData = ResponseConfig<GetOwnersIdQueryResponse>,
  TQueryKey extends QueryKey = GetOwnersIdInfiniteQueryKey,
>(
  id: GetOwnersIdPathParams['id'],
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetOwnersIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getOwnersIdInfiniteQueryKey(id)

  const query = useInfiniteQuery(
    {
      ...(getOwnersIdInfiniteQueryOptions(id, config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}