/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { DeleteUsersIdMutationResponse, DeleteUsersIdPathParams } from '../../types/DeleteUsersId'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import { useMutation } from '@tanstack/react-query'

export const deleteUsersIdMutationKey = () => [{ url: '/users/{id}' }] as const

export type DeleteUsersIdMutationKey = ReturnType<typeof deleteUsersIdMutationKey>

/**
 * @summary Delete a user
 * {@link /users/:id}
 */
export async function deleteUsersId(id: DeleteUsersIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<DeleteUsersIdMutationResponse, ResponseErrorConfig<Error>, unknown>({ method: 'DELETE', url: `/users/${id}`, ...requestConfig })
  return res
}

/**
 * @summary Delete a user
 * {@link /users/:id}
 */
export function useDeleteUsersId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<DeleteUsersIdMutationResponse>,
      ResponseErrorConfig<Error>,
      { id: DeleteUsersIdPathParams['id'] },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? deleteUsersIdMutationKey()

  return useMutation<ResponseConfig<DeleteUsersIdMutationResponse>, ResponseErrorConfig<Error>, { id: DeleteUsersIdPathParams['id'] }, TContext>(
    {
      mutationFn: async ({ id }) => {
        return deleteUsersId(id, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}