/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetUsersQueryResponse, GetUsersQueryParams } from '../../types/GetUsers'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getUsersInfiniteQueryKey = (params?: GetUsersQueryParams) => [{ url: '/users' }, ...(params ? [params] : [])] as const

export type GetUsersInfiniteQueryKey = ReturnType<typeof getUsersInfiniteQueryKey>

/**
 * @summary Get all users with pagination
 * {@link /users}
 */
export async function getUsersInfinite(params?: GetUsersQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetUsersQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/users`, params, ...requestConfig })
  return res
}

export function getUsersInfiniteQueryOptions(params?: GetUsersQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getUsersInfiniteQueryKey(params)
  return infiniteQueryOptions<
    ResponseConfig<GetUsersQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetUsersQueryResponse>,
    typeof queryKey,
    number
  >({
    queryKey,
    queryFn: async ({ signal, pageParam }) => {
      config.signal = signal

      if (params) {
        params['next_page'] = pageParam as unknown as GetUsersQueryParams['next_page']
      }
      return getUsersInfinite(params, config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * @summary Get all users with pagination
 * {@link /users}
 */
export function useGetUsersInfinite<
  TData = InfiniteData<ResponseConfig<GetUsersQueryResponse>>,
  TQueryData = ResponseConfig<GetUsersQueryResponse>,
  TQueryKey extends QueryKey = GetUsersInfiniteQueryKey,
>(
  params?: GetUsersQueryParams,
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetUsersQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getUsersInfiniteQueryKey(params)

  const query = useInfiniteQuery(
    {
      ...(getUsersInfiniteQueryOptions(params, config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}