/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetUsersUsernameQueryResponse, GetUsersUsernamePathParams } from '../../types/GetUsersUsernameUsername'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getUsersUsernameUsernameSuspenseQueryKey = (username: GetUsersUsernamePathParams['username']) =>
  [{ url: '/users/username/:username', params: { username: username } }] as const

export type GetUsersUsernameUsernameSuspenseQueryKey = ReturnType<typeof getUsersUsernameUsernameSuspenseQueryKey>

/**
 * @summary Get a user by username
 * {@link /users/username/:username}
 */
export async function getUsersUsernameUsernameSuspense(
  username: GetUsersUsernamePathParams['username'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetUsersUsernameQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/users/username/${username}`,
    ...requestConfig,
  })
  return res
}

export function getUsersUsernameUsernameSuspenseQueryOptions(
  username: GetUsersUsernamePathParams['username'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getUsersUsernameUsernameSuspenseQueryKey(username)
  return queryOptions<
    ResponseConfig<GetUsersUsernameQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetUsersUsernameQueryResponse>,
    typeof queryKey
  >({
    enabled: !!username,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getUsersUsernameUsernameSuspense(username, config)
    },
  })
}

/**
 * @summary Get a user by username
 * {@link /users/username/:username}
 */
export function useGetUsersUsernameUsernameSuspense<
  TData = ResponseConfig<GetUsersUsernameQueryResponse>,
  TQueryKey extends QueryKey = GetUsersUsernameUsernameSuspenseQueryKey,
>(
  username: GetUsersUsernamePathParams['username'],
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetUsersUsernameQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getUsersUsernameUsernameSuspenseQueryKey(username)

  const query = useSuspenseQuery(
    {
      ...(getUsersUsernameUsernameSuspenseQueryOptions(username, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}