/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetUsersIdQueryResponse, GetUsersIdPathParams } from '../../types/GetUsersId'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getUsersIdSuspenseQueryKey = (id: GetUsersIdPathParams['id']) => [{ url: '/users/:id', params: { id: id } }] as const

export type GetUsersIdSuspenseQueryKey = ReturnType<typeof getUsersIdSuspenseQueryKey>

/**
 * @summary Get a user by ID
 * {@link /users/:id}
 */
export async function getUsersIdSuspense(id: GetUsersIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetUsersIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/users/${id}`, ...requestConfig })
  return res
}

export function getUsersIdSuspenseQueryOptions(id: GetUsersIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getUsersIdSuspenseQueryKey(id)
  return queryOptions<ResponseConfig<GetUsersIdQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetUsersIdQueryResponse>, typeof queryKey>({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getUsersIdSuspense(id, config)
    },
  })
}

/**
 * @summary Get a user by ID
 * {@link /users/:id}
 */
export function useGetUsersIdSuspense<TData = ResponseConfig<GetUsersIdQueryResponse>, TQueryKey extends QueryKey = GetUsersIdSuspenseQueryKey>(
  id: GetUsersIdPathParams['id'],
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetUsersIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getUsersIdSuspenseQueryKey(id)

  const query = useSuspenseQuery(
    {
      ...(getUsersIdSuspenseQueryOptions(id, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}