/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetUsersIdQueryResponse, GetUsersIdPathParams } from '../../types/GetUsersId'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getUsersIdInfiniteQueryKey = (id: GetUsersIdPathParams['id']) => [{ url: '/users/:id', params: { id: id } }] as const

export type GetUsersIdInfiniteQueryKey = ReturnType<typeof getUsersIdInfiniteQueryKey>

/**
 * @summary Get a user by ID
 * {@link /users/:id}
 */
export async function getUsersIdInfinite(id: GetUsersIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetUsersIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/users/${id}`, ...requestConfig })
  return res
}

export function getUsersIdInfiniteQueryOptions(id: GetUsersIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getUsersIdInfiniteQueryKey(id)
  return infiniteQueryOptions<ResponseConfig<GetUsersIdQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetUsersIdQueryResponse>, typeof queryKey>({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getUsersIdInfinite(id, config)
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * @summary Get a user by ID
 * {@link /users/:id}
 */
export function useGetUsersIdInfinite<
  TData = InfiniteData<ResponseConfig<GetUsersIdQueryResponse>>,
  TQueryData = ResponseConfig<GetUsersIdQueryResponse>,
  TQueryKey extends QueryKey = GetUsersIdInfiniteQueryKey,
>(
  id: GetUsersIdPathParams['id'],
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetUsersIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getUsersIdInfiniteQueryKey(id)

  const query = useInfiniteQuery(
    {
      ...(getUsersIdInfiniteQueryOptions(id, config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}