/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetUsersUsernameQueryResponse, GetUsersUsernamePathParams } from '../../types/GetUsersUsernameUsername'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getUsersUsernameUsernameQueryKey = (username: GetUsersUsernamePathParams['username']) =>
  [{ url: '/users/username/:username', params: { username: username } }] as const

export type GetUsersUsernameUsernameQueryKey = ReturnType<typeof getUsersUsernameUsernameQueryKey>

/**
 * @summary Get a user by username
 * {@link /users/username/:username}
 */
export async function getUsersUsernameUsername(
  username: GetUsersUsernamePathParams['username'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetUsersUsernameQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/users/username/${username}`,
    ...requestConfig,
  })
  return res
}

export function getUsersUsernameUsernameQueryOptions(
  username: GetUsersUsernamePathParams['username'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getUsersUsernameUsernameQueryKey(username)
  return queryOptions<
    ResponseConfig<GetUsersUsernameQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetUsersUsernameQueryResponse>,
    typeof queryKey
  >({
    enabled: !!username,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getUsersUsernameUsername(username, config)
    },
  })
}

/**
 * @summary Get a user by username
 * {@link /users/username/:username}
 */
export function useGetUsersUsernameUsername<
  TData = ResponseConfig<GetUsersUsernameQueryResponse>,
  TQueryData = ResponseConfig<GetUsersUsernameQueryResponse>,
  TQueryKey extends QueryKey = GetUsersUsernameUsernameQueryKey,
>(
  username: GetUsersUsernamePathParams['username'],
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetUsersUsernameQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getUsersUsernameUsernameQueryKey(username)

  const query = useQuery(
    {
      ...(getUsersUsernameUsernameQueryOptions(username, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}