/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetUsersQueryResponse, GetUsersQueryParams } from '../../types/GetUsers'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getUsersSuspenseQueryKey = (params?: GetUsersQueryParams) => [{ url: '/users' }, ...(params ? [params] : [])] as const

export type GetUsersSuspenseQueryKey = ReturnType<typeof getUsersSuspenseQueryKey>

/**
 * @summary Get all users with pagination
 * {@link /users}
 */
export async function getUsersSuspense(params?: GetUsersQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetUsersQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/users`, params, ...requestConfig })
  return res
}

export function getUsersSuspenseQueryOptions(params?: GetUsersQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getUsersSuspenseQueryKey(params)
  return queryOptions<ResponseConfig<GetUsersQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetUsersQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getUsersSuspense(params, config)
    },
  })
}

/**
 * @summary Get all users with pagination
 * {@link /users}
 */
export function useGetUsersSuspense<TData = ResponseConfig<GetUsersQueryResponse>, TQueryKey extends QueryKey = GetUsersSuspenseQueryKey>(
  params?: GetUsersQueryParams,
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetUsersQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getUsersSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...(getUsersSuspenseQueryOptions(params, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}