/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { DeleteCertificatesIdMutationResponse, DeleteCertificatesIdPathParams } from '../../types/DeleteCertificatesId'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import { useMutation } from '@tanstack/react-query'

export const deleteCertificatesIdMutationKey = () => [{ url: '/certificates/{id}' }] as const

export type DeleteCertificatesIdMutationKey = ReturnType<typeof deleteCertificatesIdMutationKey>

/**
 * @summary Delete a certificate
 * {@link /certificates/:id}
 */
export async function deleteCertificatesId(id: DeleteCertificatesIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<DeleteCertificatesIdMutationResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'DELETE',
    url: `/certificates/${id}`,
    ...requestConfig,
  })
  return res
}

/**
 * @summary Delete a certificate
 * {@link /certificates/:id}
 */
export function useDeleteCertificatesId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<DeleteCertificatesIdMutationResponse>,
      ResponseErrorConfig<Error>,
      { id: DeleteCertificatesIdPathParams['id'] },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? deleteCertificatesIdMutationKey()

  return useMutation<ResponseConfig<DeleteCertificatesIdMutationResponse>, ResponseErrorConfig<Error>, { id: DeleteCertificatesIdPathParams['id'] }, TContext>(
    {
      mutationFn: async ({ id }) => {
        return deleteCertificatesId(id, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}