/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetCertificatesQueryResponse, GetCertificatesQueryParams } from '../../types/GetCertificates'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getCertificatesQueryKey = (params?: GetCertificatesQueryParams) => [{ url: '/certificates' }, ...(params ? [params] : [])] as const

export type GetCertificatesQueryKey = ReturnType<typeof getCertificatesQueryKey>

/**
 * @summary Get all certificates with pagination
 * {@link /certificates}
 */
export async function getCertificates(params?: GetCertificatesQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetCertificatesQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/certificates`,
    params,
    ...requestConfig,
  })
  return res
}

export function getCertificatesQueryOptions(params?: GetCertificatesQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getCertificatesQueryKey(params)
  return queryOptions<ResponseConfig<GetCertificatesQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetCertificatesQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getCertificates(params, config)
    },
  })
}

/**
 * @summary Get all certificates with pagination
 * {@link /certificates}
 */
export function useGetCertificates<
  TData = ResponseConfig<GetCertificatesQueryResponse>,
  TQueryData = ResponseConfig<GetCertificatesQueryResponse>,
  TQueryKey extends QueryKey = GetCertificatesQueryKey,
>(
  params?: GetCertificatesQueryParams,
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetCertificatesQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getCertificatesQueryKey(params)

  const query = useQuery(
    {
      ...(getCertificatesQueryOptions(params, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}