/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetCertificatesIdQueryResponse, GetCertificatesIdPathParams } from '../../types/GetCertificatesId'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getCertificatesIdQueryKey = (id: GetCertificatesIdPathParams['id']) => [{ url: '/certificates/:id', params: { id: id } }] as const

export type GetCertificatesIdQueryKey = ReturnType<typeof getCertificatesIdQueryKey>

/**
 * @summary Get a certificate by ID
 * {@link /certificates/:id}
 */
export async function getCertificatesId(id: GetCertificatesIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetCertificatesIdQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/certificates/${id}`,
    ...requestConfig,
  })
  return res
}

export function getCertificatesIdQueryOptions(id: GetCertificatesIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getCertificatesIdQueryKey(id)
  return queryOptions<
    ResponseConfig<GetCertificatesIdQueryResponse>,
    ResponseErrorConfig<Error>,
    ResponseConfig<GetCertificatesIdQueryResponse>,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getCertificatesId(id, config)
    },
  })
}

/**
 * @summary Get a certificate by ID
 * {@link /certificates/:id}
 */
export function useGetCertificatesId<
  TData = ResponseConfig<GetCertificatesIdQueryResponse>,
  TQueryData = ResponseConfig<GetCertificatesIdQueryResponse>,
  TQueryKey extends QueryKey = GetCertificatesIdQueryKey,
>(
  id: GetCertificatesIdPathParams['id'],
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetCertificatesIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getCertificatesIdQueryKey(id)

  const query = useQuery(
    {
      ...(getCertificatesIdQueryOptions(id, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}