/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetCertificatesQueryResponse, GetCertificatesQueryParams } from '../../types/GetCertificates'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getCertificatesSuspenseQueryKey = (params?: GetCertificatesQueryParams) => [{ url: '/certificates' }, ...(params ? [params] : [])] as const

export type GetCertificatesSuspenseQueryKey = ReturnType<typeof getCertificatesSuspenseQueryKey>

/**
 * @summary Get all certificates with pagination
 * {@link /certificates}
 */
export async function getCertificatesSuspense(params?: GetCertificatesQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetCertificatesQueryResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/certificates`,
    params,
    ...requestConfig,
  })
  return res
}

export function getCertificatesSuspenseQueryOptions(params?: GetCertificatesQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getCertificatesSuspenseQueryKey(params)
  return queryOptions<ResponseConfig<GetCertificatesQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetCertificatesQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getCertificatesSuspense(params, config)
    },
  })
}

/**
 * @summary Get all certificates with pagination
 * {@link /certificates}
 */
export function useGetCertificatesSuspense<TData = ResponseConfig<GetCertificatesQueryResponse>, TQueryKey extends QueryKey = GetCertificatesSuspenseQueryKey>(
  params?: GetCertificatesQueryParams,
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetCertificatesQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getCertificatesSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...(getCertificatesSuspenseQueryOptions(params, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}