/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { DeleteLinksIdMutationResponse, DeleteLinksIdPathParams } from '../../types/DeleteLinksId'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import { useMutation } from '@tanstack/react-query'

export const deleteLinksIdMutationKey = () => [{ url: '/links/{id}' }] as const

export type DeleteLinksIdMutationKey = ReturnType<typeof deleteLinksIdMutationKey>

/**
 * @summary Delete a link
 * {@link /links/:id}
 */
export async function deleteLinksId(id: DeleteLinksIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<DeleteLinksIdMutationResponse, ResponseErrorConfig<Error>, unknown>({ method: 'DELETE', url: `/links/${id}`, ...requestConfig })
  return res
}

/**
 * @summary Delete a link
 * {@link /links/:id}
 */
export function useDeleteLinksId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      ResponseConfig<DeleteLinksIdMutationResponse>,
      ResponseErrorConfig<Error>,
      { id: DeleteLinksIdPathParams['id'] },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? deleteLinksIdMutationKey()

  return useMutation<ResponseConfig<DeleteLinksIdMutationResponse>, ResponseErrorConfig<Error>, { id: DeleteLinksIdPathParams['id'] }, TContext>(
    {
      mutationFn: async ({ id }) => {
        return deleteLinksId(id, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}