/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetLinksQueryResponse, GetLinksQueryParams } from '../../types/GetLinks'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getLinksQueryKey = (params?: GetLinksQueryParams) => [{ url: '/links' }, ...(params ? [params] : [])] as const

export type GetLinksQueryKey = ReturnType<typeof getLinksQueryKey>

/**
 * @summary Get all links with pagination
 * {@link /links}
 */
export async function getLinks(params?: GetLinksQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetLinksQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/links`, params, ...requestConfig })
  return res
}

export function getLinksQueryOptions(params?: GetLinksQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getLinksQueryKey(params)
  return queryOptions<ResponseConfig<GetLinksQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetLinksQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getLinks(params, config)
    },
  })
}

/**
 * @summary Get all links with pagination
 * {@link /links}
 */
export function useGetLinks<
  TData = ResponseConfig<GetLinksQueryResponse>,
  TQueryData = ResponseConfig<GetLinksQueryResponse>,
  TQueryKey extends QueryKey = GetLinksQueryKey,
>(
  params?: GetLinksQueryParams,
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetLinksQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getLinksQueryKey(params)

  const query = useQuery(
    {
      ...(getLinksQueryOptions(params, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}