/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetLinksIdQueryResponse, GetLinksIdPathParams } from '../../types/GetLinksId'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getLinksIdQueryKey = (id: GetLinksIdPathParams['id']) => [{ url: '/links/:id', params: { id: id } }] as const

export type GetLinksIdQueryKey = ReturnType<typeof getLinksIdQueryKey>

/**
 * @summary Get a link by ID
 * {@link /links/:id}
 */
export async function getLinksId(id: GetLinksIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetLinksIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/links/${id}`, ...requestConfig })
  return res
}

export function getLinksIdQueryOptions(id: GetLinksIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getLinksIdQueryKey(id)
  return queryOptions<ResponseConfig<GetLinksIdQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetLinksIdQueryResponse>, typeof queryKey>({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getLinksId(id, config)
    },
  })
}

/**
 * @summary Get a link by ID
 * {@link /links/:id}
 */
export function useGetLinksId<
  TData = ResponseConfig<GetLinksIdQueryResponse>,
  TQueryData = ResponseConfig<GetLinksIdQueryResponse>,
  TQueryKey extends QueryKey = GetLinksIdQueryKey,
>(
  id: GetLinksIdPathParams['id'],
  options: {
    query?: Partial<QueryObserverOptions<ResponseConfig<GetLinksIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getLinksIdQueryKey(id)

  const query = useQuery(
    {
      ...(getLinksIdQueryOptions(id, config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}