/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetLinksIdQueryResponse, GetLinksIdPathParams } from '../../types/GetLinksId'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { InfiniteData, QueryKey, QueryClient, InfiniteQueryObserverOptions, UseInfiniteQueryResult } from '@tanstack/react-query'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'

export const getLinksIdInfiniteQueryKey = (id: GetLinksIdPathParams['id']) => [{ url: '/links/:id', params: { id: id } }] as const

export type GetLinksIdInfiniteQueryKey = ReturnType<typeof getLinksIdInfiniteQueryKey>

/**
 * @summary Get a link by ID
 * {@link /links/:id}
 */
export async function getLinksIdInfinite(id: GetLinksIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetLinksIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/links/${id}`, ...requestConfig })
  return res
}

export function getLinksIdInfiniteQueryOptions(id: GetLinksIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getLinksIdInfiniteQueryKey(id)
  return infiniteQueryOptions<ResponseConfig<GetLinksIdQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetLinksIdQueryResponse>, typeof queryKey>({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getLinksIdInfinite(id, config)
    },
    initialPageParam: 0,
    // @ts-ignore
    getNextPageParam: (lastPage) => lastPage['nextCursor'],
    // @ts-ignore
    getPreviousPageParam: (firstPage) => firstPage['nextCursor'],
  })
}

/**
 * @summary Get a link by ID
 * {@link /links/:id}
 */
export function useGetLinksIdInfinite<
  TData = InfiniteData<ResponseConfig<GetLinksIdQueryResponse>>,
  TQueryData = ResponseConfig<GetLinksIdQueryResponse>,
  TQueryKey extends QueryKey = GetLinksIdInfiniteQueryKey,
>(
  id: GetLinksIdPathParams['id'],
  options: {
    query?: Partial<InfiniteQueryObserverOptions<ResponseConfig<GetLinksIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getLinksIdInfiniteQueryKey(id)

  const query = useInfiniteQuery(
    {
      ...(getLinksIdInfiniteQueryOptions(id, config) as unknown as InfiniteQueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<InfiniteQueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseInfiniteQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}