/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetLinksIdQueryResponse, GetLinksIdPathParams } from '../../types/GetLinksId'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getLinksIdSuspenseQueryKey = (id: GetLinksIdPathParams['id']) => [{ url: '/links/:id', params: { id: id } }] as const

export type GetLinksIdSuspenseQueryKey = ReturnType<typeof getLinksIdSuspenseQueryKey>

/**
 * @summary Get a link by ID
 * {@link /links/:id}
 */
export async function getLinksIdSuspense(id: GetLinksIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetLinksIdQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/links/${id}`, ...requestConfig })
  return res
}

export function getLinksIdSuspenseQueryOptions(id: GetLinksIdPathParams['id'], config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getLinksIdSuspenseQueryKey(id)
  return queryOptions<ResponseConfig<GetLinksIdQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetLinksIdQueryResponse>, typeof queryKey>({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getLinksIdSuspense(id, config)
    },
  })
}

/**
 * @summary Get a link by ID
 * {@link /links/:id}
 */
export function useGetLinksIdSuspense<TData = ResponseConfig<GetLinksIdQueryResponse>, TQueryKey extends QueryKey = GetLinksIdSuspenseQueryKey>(
  id: GetLinksIdPathParams['id'],
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetLinksIdQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getLinksIdSuspenseQueryKey(id)

  const query = useSuspenseQuery(
    {
      ...(getLinksIdSuspenseQueryOptions(id, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}