/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { GetLinksQueryResponse, GetLinksQueryParams } from '../../types/GetLinks'
import type { RequestConfig, ResponseErrorConfig, ResponseConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getLinksSuspenseQueryKey = (params?: GetLinksQueryParams) => [{ url: '/links' }, ...(params ? [params] : [])] as const

export type GetLinksSuspenseQueryKey = ReturnType<typeof getLinksSuspenseQueryKey>

/**
 * @summary Get all links with pagination
 * {@link /links}
 */
export async function getLinksSuspense(params?: GetLinksQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetLinksQueryResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/links`, params, ...requestConfig })
  return res
}

export function getLinksSuspenseQueryOptions(params?: GetLinksQueryParams, config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getLinksSuspenseQueryKey(params)
  return queryOptions<ResponseConfig<GetLinksQueryResponse>, ResponseErrorConfig<Error>, ResponseConfig<GetLinksQueryResponse>, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getLinksSuspense(params, config)
    },
  })
}

/**
 * @summary Get all links with pagination
 * {@link /links}
 */
export function useGetLinksSuspense<TData = ResponseConfig<GetLinksQueryResponse>, TQueryKey extends QueryKey = GetLinksSuspenseQueryKey>(
  params?: GetLinksQueryParams,
  options: {
    query?: Partial<UseSuspenseQueryOptions<ResponseConfig<GetLinksQueryResponse>, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getLinksSuspenseQueryKey(params)

  const query = useSuspenseQuery(
    {
      ...(getLinksSuspenseQueryOptions(params, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}