/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { PostLinksMutationRequest, PostLinksMutationResponse } from '../../types/PostLinks'
import type { RequestConfig, ResponseConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import { useMutation } from '@tanstack/react-query'

export const postLinksMutationKey = () => [{ url: '/links' }] as const

export type PostLinksMutationKey = ReturnType<typeof postLinksMutationKey>

/**
 * @summary Create a new link
 * {@link /links}
 */
export async function postLinks(data: PostLinksMutationRequest, config: Partial<RequestConfig<PostLinksMutationRequest>> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<PostLinksMutationResponse, ResponseErrorConfig<Error>, PostLinksMutationRequest>({
    method: 'POST',
    url: `/links`,
    data,
    ...requestConfig,
  })
  return res
}

/**
 * @summary Create a new link
 * {@link /links}
 */
export function usePostLinks<TContext>(
  options: {
    mutation?: UseMutationOptions<ResponseConfig<PostLinksMutationResponse>, ResponseErrorConfig<Error>, { data: PostLinksMutationRequest }, TContext> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig<PostLinksMutationRequest>> & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? postLinksMutationKey()

  return useMutation<ResponseConfig<PostLinksMutationResponse>, ResponseErrorConfig<Error>, { data: PostLinksMutationRequest }, TContext>(
    {
      mutationFn: async ({ data }) => {
        return postLinks(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}